### ISSUE TITLE
converge wipes out state and recreates from scratch without destroy

### ISSUE THREAD

**Issue by johnrengelman** [newcontext-oss/kitchen-terraform#102]
Running `kitchen converge` twice in a row results in duplicate resources. This is with version 0.6.0. I'm fairly certain this wasn't occurring in 0.5.0 so it's a regression.

`kitchen converge` should maintain the existing state file and only apply the differences.

**Comment by ncs-alane** [comment]
That is definitely not intended behaviour! I'll take a look at the code and review #103.
