### ISSUE TITLE
Add support for wrapper scripts like terragrunt

### ISSUE THREAD

**Issue by mixtli** [newcontext-oss/kitchen-terraform#105]
So, my use case is that I have a repository structured something like this:

myapp/
  module/
     main.tf
     etc..
  environments/
    dev/
       main.tf
    prod/
       main.tf

In each environments folder is a .terragrunt that describes how to access the state.  I want to be able to run test-kitchen for each environment using the existing remote state.   So I'm planning on running in live environments (verify only).  I managed get it working with straight terraform by hijacking the 'platform' concept in .kitchen.yml to support environments by overriding the 'directory' parameter per environment.

I tried using the new cli parameter to use the terragrunt binary, but there are two problems:
1)  When I run converge, it immediately fails because apparently it tries to run terragrunt version which fails if there is no .terragrunt file in the root directory.
2) If I "touch .terragrunt" it gets past that part, but then it still passes a --state parameter to terragrunt, which causes it to not use the remote state, but generate a new state in .kitchen/kitchen-terraform/default-dev/terraform.tfstate for example. 

I'd like to be able to suppress the --state argument somehow so that it will use the terragrunt state from the "directory" specified by the provisioner overrides for the "platform" (environment).
And I'd like it to run all terraform/terragrunt commands from that directory.

Is there a way to do it I'm just not thinking about?   Also, I'd be happy to make a PR when I get some time, but some pointers to places in the code that I'd need to change would save me a lot of time.

Thanks!

**Comment by ncs-alane** [comment]
@mixtli: thanks for your interest in the project!

I don't think there is currently a way to accomplish what you want to do but it should be possible to implement the behaviour. I'll have to think about the design for a bit.

@elijah do you have any input regarding terragrunt?

**Comment by ncs-alane** [comment]
Mechanism to set the working directory: https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout.rb#L54

**Comment by ncs-alane** [comment]
@mixtli: the `.terragrunt` file has been [deprecated](https://github.com/gruntwork-io/terragrunt#terragrunt-config-files), so it seems like upgrading will also solve your first point.

**Comment by ncs-alane** [comment]
@mixtli: can you clarify if it is local state files or remote states that you are wanting to work with?

**Comment by mixtli** [comment]
Ah, yes, the first issue is no longer an issue.   I want to work with the remote state exclusively.

**Comment by ncs-alane** [comment]
@mixtli:

Since you no longer need this feature, I'm going to close this issue until an other case is made for it.
