### ISSUE TITLE
Show Terraform state location after it changes

### ISSUE THREAD

**Issue by kevindickerson** [newcontext-oss/kitchen-terraform#106]
Test Kitchen commands can result in changes to the Terraform state file regardless of the success or failure of the command. kitchen-terraform should inform or provide an option to inform) the user of the location of the Terraform state file after any action that updates the Terraform plan.

**Comment by ncs-alane** [comment]
@kevindickerson:

Did you mean to write:
> ...the location of the Terraform _state_ file after any action that updates the Terraform _state_

❔

**Comment by kevindickerson** [comment]
Yes, updated. State file.
