### ISSUE TITLE
Show Terraform plan location after it changes

### ISSUE THREAD

**Issue by kevindickerson** [newcontext-oss/kitchen-terraform#107]
Test Kitchen commands can result in changes to the Terraform plan file regardless of the success or failure of the action. kitchen-terraform should inform (or provide an option to inform) the user of the location of the Terraform plan file after any action that updates the Terraform plan.

**Comment by kevindickerson** [comment]
I take this back. I don't know if indicating that the plan changed is useful at all. The state is much more important.

**Comment by ncs-alane** [comment]
@kevindickerson:

It's trivial enough to log the pathname of each file that we may as well do both.

**Comment by kevindickerson** [comment]
Well, I guess my thought was: Is the plan file actually useful for either a) humans authoring and testing Terraform code or b) humans debugging an issue by inspecting logs?
