### ISSUE TITLE
When the transport SSH key is not found or has incorrect permissions, fail and notify the user

### ISSUE THREAD

**Issue by kevindickerson** [newcontext-oss/kitchen-terraform#110]
Given a .kitchen.yml file similar the following example, notify the user and fail if the certificate is not found. It should also check for permissions other than `0400` and fail accordingly if access is too unrestricted.

Affected conditions:
- ./certificates/example.pem does not exist
- ./certificates/example.pem exists but has unrestricted permissions

```YAML
transport:
  ssh_key: certificates/example.pem
```

Currently Test Kitchen will time out, and does not provide a useful message. The message should provide useful output so the user can correct either their certificate, or their .kitchen.yml file.

**Comment by ncs-alane** [comment]
@kevindickerson:

This could be managed here, but we could also propose it as a pull-request on the [Test Kitchen SSH transport plugin](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/ssh.rb).

```ruby
required_config :ssh_key do |_, ssh_key|
  ::File.exist? ssh_key or raise ::Kitchen::UserError
  # additional check for correct permissions
end
```

**Comment by aaron-lane** [comment]
This behaviour is now the responsibility of InSpec.
