### ISSUE TITLE
support terraform 0.9 and backends

### ISSUE THREAD

**Issue by mixtli** [newcontext-oss/kitchen-terraform#112]
So, terraform 0.9 now supports remote state 'backends' with state locking, so I'm no longer using terragrunt (https://github.com/newcontext-oss/kitchen-terraform/issues/105).   Any chance of getting support for 0.9 soon?

**Comment by ncs-alane** [comment]
@mixtli:

[Support for Terraform 0.9 is planned for kitchen-terraform 0.7](https://github.com/newcontext-oss/kitchen-terraform/pull/108). Unfortunately, after debugging [a test failure in that effort](https://travis-ci.org/newcontext-oss/kitchen-terraform/jobs/213734272#L1225), I discovered [a bug in Terraform 0.9 that breaks the kitchen-terraform workflow](https://github.com/hashicorp/terraform/issues/12969). Once that bug is resolved, we can wrap up 0.7 and ship it!

**Comment by dlen** [comment]
Hi!

Thanks for your efforts on delivering such a good tool I find it very useful. However, I'm wondering if the support for remote state backends is working on kitchen-terraform as I'm facing issues when using an s3 backend for state storage.
When terraform is configured to use a remote state backend such as s3 it doesn't allow using `terraform apply` with `-state` or `-state-out`. Running kitchen-terraform using `kitchen verify` it outputs the following:
```STDOUT:                                     
STDERR: Failed to load backend: The -state and -state-out flags cannot be set with a plan that has a remote```
I haven't found a way to disable `-state` and `-state-output` when running terraform command from the kitchen-terraform wrapper and seems to me that state option on .kitchen.yaml is designed to be a local path (correct me if I'm wrong)
Any ideas?

**Comment by ncs-alane** [comment]
@dlen:

Thank you for your interest in the project! While Terraform 0.9 is supported, explicit support for remote state has not yet been implemented. We are hoping to implement support for the upcoming release of  kitchen-terraform 1.0.

**Comment by dlen** [comment]
@ncs-alane Thanks for your reply! Support for terraform environments I guess is in the same situation am I right?

**Comment by ncs-alane** [comment]
@dlen that is indeed my current estimate.

**Comment by anosulchik** [comment]
@ncs-alane It looks like kitchen-terraform 1.0 is already out but it still doesn't support remote backends. Can you please comment if it's planned implementing it in further versions?

We have the following section in terraform config that we would like to tests using kitchen-terraform but it fails until we comment out `backend` line:

```
terraform {
  required_version = "> 0.9.0"
  backend "s3" {}
}
```

Please advise. Thank you!

**Comment by ncs-alane** [comment]
@anosulchik: thank you for your interest in the project!

kitchen-terraform version 2.0 was recently released. It supports Terraform version ~> 0.10.2 which will allow you to work with backends.

https://rubygems.org/gems/kitchen-terraform/versions/2.0.0

**Comment by anosulchik** [comment]
Yeah, I've just updated kitchen-terraform to 2.0.0 - it seems I'll have to update terraform from 0.9 to 0.10 as well to use kitchen-terraform with remote backends. Thank you!
