### ISSUE TITLE
Issue with variable_files not loading

### ISSUE THREAD

**Issue by davidbegin** [newcontext-oss/kitchen-terraform#126]
I have been having a problem with my variable_files not loading and have isolated the commit that breaks it. 

Here is a repo to reproduce the issue: https://github.com/davidbegin/infratest 

I made this repo following the AWS getting_started guide, and have notes in my Gemfile on my findings on the kitchen-terraform commits that break running `bundle exec kitchen converge`.

I haven't looked into the details of what was changed in the commits that break it, but I will once I have more time. Only deeper debugging I have done, is I threw a pry around here: https://github.com/newcontext-oss/kitchen-terraform/blob/master/lib/kitchen/driver/terraform.rb#L197-L207 and confirmed that variable_files was indeed an empty array.

Also I am using Terraform 0.9.8.

Thanks for making the project!

**Comment by ncs-alane** [comment]
@davidbegin:

I believe the issue is the getting started guide was not updated to reflect the changes of 1.0.0 which moved all provisioner configuration to the driver. If you move `variable_files` to the driver configuration, it should work.

**Comment by davidbegin** [comment]
Excellent, later tonight I will test that change out.

**Comment by davidbegin** [comment]
That indeed fixed the problem, so closing this issue.

Thanks!
