### ISSUE TITLE
Support Terraform 0.10.x

### ISSUE THREAD

**Issue by toddmichael** [newcontext-oss/kitchen-terraform#132]
Presume this is __WIP__, but filing this request __just in case__. If it's unhelpful, feel free to close and point me to the proper enhancement request.  Thanks for your continuing effort on this fantastic project.

**Comment by ncs-alane** [comment]
@toddmichael: hello once again!

Support for Terraform 0.10 is indeed in progress! #129 and #130 will be the places to watch for that effort. I have some more local work to commit which is getting close to implementing support.

**Comment by toddmichael** [comment]
Thanks @ncs-alane. I'm sorry I proved absolutely worthless in beta testing your work before master merge; I just haven't been able to get off the mat for the past few weeks due to work & family priorities. I plan to get back to heavy Terraform work in 1-2 weeks and will report any issues.  This project has been absolutely invaluable to me and I appreciate your talent and diligence.  Be well.

**Comment by ncs-alane** [comment]
@toddmichael no problem at all! That's what patch releases are for. :grinning:
