### ISSUE TITLE
Sleep on terraform verifier

### ISSUE THREAD

**Issue by gbergere** [newcontext-oss/kitchen-terraform#134]
Hi, 

Is there a way to sleep before run the verifier in order to make sure the machines finished to provision before we run the tests on it ?

My issue is because I have one machine which run a docker images and the test are ran before the docker image have been downloaded so it fail...

Cheers

**Comment by ncs-alane** [comment]
@gbergere: the solution [used in the AWS provider example](https://github.com/newcontext-oss/kitchen-terraform/blob/master/examples/aws_provider/.kitchen.yml#L10) is to increase the number of connection retries of the Test Kitchen SSH transport. Alternatively, you could wrap the Test Kitchen commands in a script that provides some orchestration logic.

**Comment by gbergere** [comment]
@ncs-alane sure I updated  my logic in my travis script. 

Thanks
