### ISSUE TITLE
converge shows failure status even terraform apply succeeded

### ISSUE THREAD

**Issue by af6140** [newcontext-oss/kitchen-terraform#135]
in log file all resources created successfully and nothing failed after kitchen-converge. The terraform run is to create a security group with rules, nothing else.

       module.example.aws_security_group_rule.db_allow_inbound_access: Creating...
         from_port:                "" => "3306"
         protocol:                 "" => "tcp"
         security_group_id:        "" => "sg-xxxxxx"
         self:                     "" => "false"
         source_security_group_id: "" => "sg-xxxxxxx"
         type:                     "" => "ingress"
       module.example.aws_security_group_rule.self_access: Creation complete (ID: sgrule-xxxxxxxx)
       module.example.aws_security_group_rule.db_allow_all_outbound: Creation complete (ID: sgrule-xxxxxxxxxx)
       Interrupt received.
       Please wait for Terraform to exit or data loss may occur.
       Gracefully shutting down...
       stopping apply operation...
       
       Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
       
       The state of your infrastructure has been saved to the path
       below. This state is required to modify and destroy your
       infrastructure, so keep it safe. To inspect the complete state
       use the `terraform show` command.
       
       State path: /home/xxxxx/aws/tf-example_module/.kitchen/kitchen-terraform/example-rds/terraform.tfstate
       
       Outputs:
       
       security_group_id = sg-xxxxxxx
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Create failed on instance <example-rds>.  Please see .kitchen/logs/example-rds.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
****

**Comment by ncs-alane** [comment]
Hi @af6140:

Thank you for your interest in the project!

Can you provide the output of `kitchen converge --log-level=debug`?

**Comment by af6140** [comment]
Have not tried debug  yet, but found out it may be related to a ingress rule for the same security group access.

**Comment by af6140** [comment]
Turns out i need to use self="true" for self ingress other than source_security_group_id
