### ISSUE TITLE
[question] kitchen-terraform and testinfra verifier

### ISSUE THREAD

**Issue by m4h3** [newcontext-oss/kitchen-terraform#138]
Hello,

I'm not very familiar with kitchen-ci, but I didn't find the information whether or not it is possible to use a different verifier instead of inspec based terraform verifier ?

The main point is, how to we get provioner terraform hostname outputs to other kind of provisioners.

**Comment by m4h3** [comment]
"kitchen-terraform provides three Test Kitchen plugins which must be used together [...]"

I guess that is the answer.

**Comment by ncs-alane** [comment]
@m4h3:

Thank you for your interest in the project!

While kitchen-terraform is currently limited to using InSpec, the ability to use alternative testing frameworks is going to be explored for an upcoming release. Additionally, better documenation will hopefully address some of the uncertainty around using kitchen-terraform.
