### ISSUE TITLE
Invoke terraform via docker rather than the executable in the system's path

### ISSUE THREAD

**Issue by brandoconnor** [newcontext-oss/kitchen-terraform#145]
I've had good experiences as of late running terraform from [docker via the registry](https://hub.docker.com/r/hashicorp/terraform/) and think this would be a better way to have kitchen-terraform invoke terraform. To me, the real value here would be the ability to run over tests over a matrix of terraform versions but also to care less about how terraform is installed on build machines.

Wondering if this is in the cards for the direction of this project or not. It's been years since I've written any Ruby and that was mostly Chef but I could take a stab at the PR if maintainers agree this is a worthwhile effort. Thoughts?

Would resolve this: https://github.com/newcontext-oss/kitchen-terraform/issues/120
Can't tell if this is related or not: https://github.com/newcontext-oss/kitchen-terraform/issues/92

**Comment by ncs-alane** [comment]
Hi @brandoconnor:

Thank you for your interest in the project!

I am hesitant about introducing Docker as a required dependency for using kitchen-terraform but I am intrigued by what you a proposing. Can you expand on how this would work?

**Comment by brandoconnor** [comment]
No problem. Let me try to add some detail.

For the moment, kitchen-terraform is bound to the version of terraform installed locally to the system's path. Without modification of PATH, the actual terraform binary itself, or through some trickery like aliasing or brew commands, kitchen-terraform is stuck (at least when running tests locally) to a single version of terraform. If I wanted to run tests locally against a number of terraform versions, there'd be a lot of manual orchestration to make that happen. CI systems, depending on capability, might be able to get around it with parallel build machines each installing different versions of terraform or sequentially executing the same test suites using different terraform binaries from test run to test run. I don't think this is quite ideal but maybe you have examples of this looking reasonably good.

Enter the proposed alternative here: terraform as invoked via Docker. I think we have an easier story to tell for the setup of terraform while improving the ability to test several versions of terraform for modules or entire infrastructures. The Docker registry lists terraform light [containers by tag](https://hub.docker.com/r/hashicorp/terraform/tags/) so instead of a version (or set of versions) of terraform being implicitly required by kitchen-terraform on a module by module basis, terraform version information could be captured within .kitchen.yml itself and used to spin up resources using the necessary container version(s):

```
driver:
  name: "terraform"
```
Could become something like:
```
driver:
  name: "terraform"
  version: "0.10.7"
```
It's not so dissimliar from being able to specify multiple platforms each running different versions of Chef [as shown here](https://gist.github.com/fnichol/77c9ba7c64d9b6efa936#file-kitchen-yml)... Looking closer now, the build matrix is usually established using the platforms section but kitchen-terraform doesn't seem to have any interaction there. That'd be the ideal place to add version details.

I definitely see the concern about making docker rather than terraform a dependency here. It seems tangential to what we're actually trying to do (test via terraform) but I think this could definitely ease the process of terraform upgrades and make modules a little more consumable by more easily backing tests with explicit versions of terraform that it works against.

If you're looking for a different angle on the "how", [this line](https://github.com/newcontext-oss/kitchen-terraform/blob/master/lib/kitchen/terraform/client/command.rb#L144) looks to be what invokes terraform on the test host. That line would probably need to read: 
`docker run -i -t hashicorp/terraform:light #{subcommand} #{options}".strip,`
along with adding the necessary bits to provide a version of the container to pull and a pre-flight verification that a docker daemon is indeed running.

Hopefully that helps clarify. Let me know if any of the above needs more/better words.

**Comment by ncs-alane** [comment]
@brandoconnor 

:clap: 

I like what you're proposing. I think the ability to specify versions of Terraform to be managed by kitchen-terraform would be a valuable feature. I'm still not sold on using Docker to manage the process as similar behaviour could be achieved natively in Ruby without introducing an additional technology dependency. Of course, using a tool like Docker offers the ability to avoid duplicate downloads for different projects being tested. I guess it's a tradeoff to be discussed. 

Hopefully some other members of the community will offer their thoughts, but I think it's safe to say at an abstract level that this behaviour will be shipped in an upcoming major release.

**Comment by eamonnfaherty** [comment]
+1 for me.  Using docker makes sense as I already run all my terraform commands from a docker container.
