### ISSUE TITLE
Set `TF_IN_AUTOMATION` environment variable to a non-empty value

### ISSUE THREAD

**Issue by ncs-alane** [newcontext-oss/kitchen-terraform#149]
As per the [Controling Terraform Output in Automation article](https://www.terraform.io/guides/running-terraform-in-automation.html#controlling-terraform-output-in-automation), `TF_IN_AUTOMATION` should be set to a non-empty value when kitchen-terraform plugins take actions.

**Comment by edwardbartholomew** [comment]
👍
