### ISSUE TITLE
Add Instructions/Documentation for pulling existing infra into kitchen-terraform non-destructively.

### ISSUE THREAD

**Issue by armenr** [newcontext-oss/kitchen-terraform#153]
Per @ncs-alane, I'm opening this separate Issue to track the documentation request. 

It would be very helpful (and much less scary for new adopters) if there were a section in the README/Documentation for how one can safely and easily factor kitchen-terraform into existing, deployed infrastructure code.

**Comment by ncs-alane** [comment]
@armenr: is the infrastructure in question part of an existing test environment or a production-like environment?

While it is technically possible to manage any environment with kitchen-terraform, I  recommend that it should not used to manage production-like environments as the workflow is strongly opinionated for an automated cycle of creation and destruction with limited safe guards in place.

**Comment by armenr** [comment]
Good point. Let's nix the request. It was ill-advised.
