### ISSUE TITLE
ecs_container_instance cant find agent_connected method

### ISSUE THREAD

**Issue by rgokhale** [newcontext-oss/kitchen-terraform#168]
I am trying to write awspec tests for a ecs cluster

```
cluster_name =  attribute "cluster_name", {}

control 'ecs_container_instance' do
  describe 'ecs_container_instance' do
    let :example_ecs_container_instance do
      ecs_container_instance('xyz') 
    end

    describe "container_instance_exists" do
      subject do example_ecs_container_instance end
      it "exists" do is_expected.to exist end
    end
    describe "container_instance_agent" do
      subject do example_ecs_container_instance.agent_connected end
      it "connected" do is_expected.to eq 0 end
    end

  end
end
```

Both tests fail with 

```
Failures:

  1) ecs_container_instance container_instance_exists exists
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected ecs_container_instance 'xyz' to exist
     # ./test/integration/local/controls/instance_specs.rb:15:in `block (4 levels) in load_with_context'

  2) ecs_container_instance container_instance_agent connected
     Failure/Error: super unless self.respond_to?(:resource)
     
     NoMethodError:
       undefined method `agent_connected' for ecs_container_instance '34df416f-888b-4794-b30f-1a96ba57d90b':Awspec::Type::EcsContainerInstance
     # ./test/integration/local/controls/instance_specs.rb:24:in `block (4 levels) in load_with_context'
     # ./test/integration/local/controls/instance_specs.rb:25:in `block (4 levels) in load_with_context'

Finished in 0.36414 seconds (files took 1.79 seconds to load)
2 examples, 2 failures

```

I definitely know the container exists
Not sure why it cant find the agent_connected method.
Maybe I am missing the cluster name, but not sure where to pass it.

Appreciate any help.

Thanks,
Rishi

**Comment by ncs-alane** [comment]
@rgokhale: it appears that the failures that you are experiencing are caused by awspec, not by Kitchen-Terraform. Have you reviewed the [documentation](https://github.com/k1LoW/awspec/blob/master/doc/_resource_types/ecs_container_instance.md#exist) and requested help from that project's maintainer?

**Comment by rgokhale** [comment]
@ncs-alane , Thanks for the very quick response. That does make sense, I can certainly ask for help there. I know have one question though, what the right way to pass the cluster name here. As shown below ecs_container_instance needs the cluster name

```
describe ecs_container_instance('xyz'), cluster: 'my-ecs-cluster' do
  it { should exist }
end
```
I need to be able to pass that here

```
let :example_ecs_container_instance do
      ecs_container_instance('xyz') 
    end
```

Thanks again.
Rishi

**Comment by ncs-alane** [comment]
@rgokhale:

Because you are retrieving the cluster name attribute at the beginning of the control, you should be able to pass that value to the method.

```ruby
cluster_name =  attribute "cluster_name", {}

control 'ecs_container_instance' do
  describe 'ecs_container_instance' do
    let :example_ecs_container_instance do
      ecs_container_instance(
        'xyz',
        cluster: cluster_name
      ) 
    end
    # ...
  end
end
```

In order for that `"cluster_name"` attribute to be populated, your Test Kitchen configuration file must include attribute configuration for the verifier group that is being evaluated. More information can be found in the [verifier documentation](http://www.rubydoc.info/gems/kitchen-terraform/3.0.0/Kitchen/Verifier/Terraform).

**Comment by rgokhale** [comment]
I did try that, but after trying that and trying to check the value of example_ecs_container_instance.cluster, its still shows the cluster as default. I also hardcoded the cluster value to rule out any issues with my cluster_name attribute.

Thanks very much.
Rishi

**Comment by ncs-alane** [comment]
@rgokhale:

Sorry that I can't be of more assistance. On the upside, it sounds like Kitchen-Terraform is working for you as expected. :+1:
