### ISSUE TITLE
Track ongoing development of https://github.com/chef/inspec-aws wrt tutorials

### ISSUE THREAD

**Issue by aaronlippold** [newcontext-oss/kitchen-terraform#170]
@ncs-alane https://github.com/chef/inspec-aws may be useful in your tutorials. 

It may help clean up the examples and core tests for easier uptake especially when we push the AWS resources into the inspec mainline ( targeting for Q1 of 2018 ). Good work and will be using kitchen-terraform in a demo very soon.

**Comment by ncs-alane** [comment]
@aaronlippold: thank you for your interest in the project!

I did look at inspec-aws recently but I was unsuccessful in making it go. I'm in favour of using it in the examples, but I would also like to maintain some sort of custom library sample (assuming inspec-aws would cover EC2 instance security groups). Do you have any thoughts?

Also, we are blocked from progressing past InSpec 1.44.8 until 2018-03-31 when Ruby 2.2 hits end of life. :ear_of_rice:

**Comment by aaronlippold** [comment]
@ncs-alane hi aaron, yes, my team ( here at MITRE ) is actually working on the https://github.com/chef/inspec-aws/pull/135 and @cwolf and I have been coordinating back and forth on pushing the aws resources as well as the azure and gcs resources once we have a working baseline of AWS. The short term goal is to demo 'security-groups' and 's3 bucket and elements' validation. The later term goal we are working towards is the fully implement https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf as well as fill in the gaps of s3 buckets, bucket elements and security groups and all the little things that CIS seemed to ignore :). We are also going to be pushing on the bastion host PRs as well for train and inspec. The challenge I have with some of examples is that it utilized customize resources and second, uses the technically correct but very much less readable expect syntax style. As a community we are trying to push for the more readable describe/should/its style overall. My hope is I can get the chec/aws folks to use kitchen-terraform in on their side as well for community sync given they are using terraform for the core integration and unit testing on inspec-aws work. Lastly, when we move to the azure and other platform resources - kitchen-terraform should give us a single approach etc.

**Comment by aaronlippold** [comment]
Looking forward to working with you on this
