### ISSUE TITLE
Add verifier configuration attribute to support remote InSpec profiles

### ISSUE THREAD

**Issue by superyarick** [newcontext-oss/kitchen-terraform#173]
It would be nice if one could specify a git location for verifier profile.
Example.
```
        - name: tmp
          git: https://github.com/nathenharvey/tmp_compliance_profile.git
```

**Comment by aaronlippold** [comment]
Please see https://github.com/chef/kitchen-inspec#use-remote-inspec-profiles.

**Comment by ncs-alane** [comment]
Usage of `inspec_tests` in kitchen-inspec: https://github.com/chef/kitchen-inspec/blob/v0.20.0/lib/kitchen/verifier/inspec.rb#L149

**Comment by aaron-lane** [comment]
Note: remote profiles can currently be invoked as describe in [the InSpec Profile Dependencies article](https://www.inspec.io/docs/reference/profiles/#profile-dependencies).
