### ISSUE TITLE
Keep `kitchen-terraform` verifier in 'feature parity' with inspec verifier.

### ISSUE THREAD

**Issue by aaronlippold** [newcontext-oss/kitchen-terraform#174]
The `controls:` and `attrs:` and `attribute:` flags in the verifier are close to the concept of `groups:` but the ability to pass these three things make it very easy to dynamically and programmatically adjust the validation profile given the environment or pipeline etc.

**Comment by ncs-alane** [comment]
@aaronlippold: I would like to better understand your request.

Each group of the Terraform verifier's configuration `groups` attribute can be configured with a unique subset of controls from the associated InSpec profile using the nested `controls` attribute. Is there additional behaviour for the `controls` attribute that you are interested in?

The `attributes` attribute of the Terraform verifier's configuration only supports the use of Terraform outputs. Are you interested in providing arbitrary values for the `attributes` attribute outside of the Terraform configuration?

**Comment by aaronlippold** [comment]
@ncs-alane 

- Item 1:  

The support for the `controls:` flag goes along with the `inspec_tests` support ( as will the `tags:` once that is merged in. The idea is that if I reference a profile source - such as a git repo or an http location or path - I can also tailor the subset of `controls` by control and or `controls with tag x` during the the test run. Many users - such as SIMP and my teams - use the two in combination to keep `hardening profiles` and `validation profiles` logically separated so that updates to a validation profile - such as rhel7, nginx or cis-aws-foundations-benchmark don't become hard linked to a specific hardening method - such as the bash, bosh, chef, puppet, terraform that may configure them. Teams may use various technologies to harden and configure capabilities but we want them all to be able to easily use the independent inspec profiles to validate the work of those methods.

- Item 2:  

The `attributes` for the `converge` phase should be connected to terraform yes, but the attributes for the `verifier` are inspec's attributes system so that the profile can 'flex' for instance and point-in-time deployments. A profile allows for a yaml file that can be hosted with the profile or passed in at execution time to override defaults in the core profile to adjust to the scope or environment for the 'instance under evaluation'. There are times I can see that the `outputs` and `variables` of the terraform run could be passed to `inspec` variables to tie the two activities together. 

For example, in our current demo we are having terraform generate a semi-random bucket name and validating it. We are using fixtures to capture that dynamic configuration but the more correct way to do this from an inspec world view is something like: ( sudo-code )

Given that we have TF code such as:
```
output "s3_public_bucket_name" {
  value = "${aws_s3_bucket.aws_demo_public_bucket.id}"
}

output "s3_private_bucket_name" {
  value = "${aws_s3_bucket.aws_demo_private_bucket.id}"
}
```
```
verifier:
  name: terraform
  groups:
    - name: aws-demo-baseline
  attributes:
    - s3_buckets_pub: ["${tfoutput.s3_public_bucket_name}","shared-bucket"]
    - s3_buckets_pri: ["${tfoutput.s3_private_bucket_name}", "corp_secrets","payroll-backup"]
```
and the new InSpec control may look like:

```
S3_BUCKETS_PUB = attribute('s3_buckets_pub',description: "my pub buckets", default: ["shared-bucket"])
S3_BUCKETS_PRI = attribute('s3_buckets_pri',description: "my pub buckets", default: ["corp_secrets","payroll-backup"])

control "public-buckets" do
  impact: 0.9
  title: "Ensure only allowed buckets are public"
  desc: "Don't get in the newspaper"
  tag "nist": ['AC-7']
  
  describe aws_s3_buckets.where { permission: pubic } do
    its('buckets') { should be_in S3_BUCKETS_PUB }
    its('buckets') { should_not be_in S3_BUCKETS_PRI }
  end
end

control "private-buckets" do
  impact: 0.9
  title: "Ensure only allowed buckets are private"
  desc: "My voice is my password"
  tag "nist": ['AC-7']
  
  describe aws_s3_buckets.where { permission: private } do
    its('buckets') { should_not be_in S3_BUCKETS_PUB }
    its('buckets') { should be_in S3_BUCKETS_PRI }
  end
end
```    

In the end I should never really have to change the validation profile at all because it uses attributes to generalize the changing data. I.e. I can have and "approved" test that I can digitally sign and people can reuse.  The data I pass in to the test can flex but I can 'lock' an approved and validated test that can be "trusted". This is the goal we are going for - and the pattern we would like to push to the infrastructure layer as well.

Now - reviewing some of the conventions - we may be able to achieve a lot of this with fixtures but I was hoping to keep the 'responsibility' for each phase inside its own wheelhouse. 

We have had some success using fixtures to generalize some of this but that won't transfer if 'something other than terraform' builds the AWS or Azure or whatnot, so using the InSpec attribute system and being able to pass TF attribute data to those is the loosely coupled approach in my way of thinking.
