### ISSUE TITLE
Tutorial sources removed since e81d200

### ISSUE THREAD

**Issue by ringods** [newcontext-oss/kitchen-terraform#183]
Since commit https://github.com/newcontext-oss/kitchen-terraform/commit/e81d2004356e3efcca3d30855a61d8b8748ff2ab, the sources for the tutorials, except the Docker one, are removed from the repo. Please restore them.

**Comment by ncs-alane** [comment]
Hi @ringods: thank you for your interest in the project!

We realized that this change made it more difficult to follow along with the tutorials so we are exploring how to bring back the functional examples and keep them in sync with the articles.
