### ISSUE TITLE
kitchen-terraform only as a provisioner?

### ISSUE THREAD

**Issue by ringods** [newcontext-oss/kitchen-terraform#199]
If I'm not mistaken, `kitchen-terraform` can only be use as `driver`, `provisioner` and `verifier` at the same time. I want to use another driver to set up my "local cloud" first.

For [terraform-provider-xenserver](https://github.com/ringods/terraform-provider-xenserver), I would like to create a `test-kitchen` setup like this:
* `vagrant` driver to set up specific Xenserver versions for various test suites
* `kitchen-terraform` provisioner to create `terraform-provider-xenserver` resources against that XenServer instance.
* `kitchen-terraform` verifier to validate the correct resource state.

Would it be possible to provide the functionality of this project by only implementing the provisioner interface?

**Comment by ncs-alane** [comment]
@ringods thank you for your interest in the project!

I do not think it is feasible to isolate the dependency on Terraform to the provisioner plugin. The driver plugin provides the `create` and `destroy` actions, and while the `create` logic could arguably be moved to the provisioner's `converge` action, the driver's `destroy` action is required to destroy the Terraform state.

Is it possible to configure xenserver for your use case using Terraform? Wrapping a Terraform module with a test fixture configuration to enable testing is an emerging pattern in this space.

**Comment by ringods** [comment]
@ncs-alane thanks for your closing remark. I'll see how far I can get by using the [terraform-provider-virtualbox](https://github.com/ccll/terraform-provider-virtualbox) to set up my XenServer VM first, before I try to create the XenServer resources via the XenServer provider I have under test.

Do you have pointers to examples of that emerging pattern where TF modules are wrapped by a test fixture?

**Comment by ncs-alane** [comment]
The project from our advanced AWS tutorial uses this pattern: https://github.com/newcontext-oss/kitchen-terraform/blob/ncs-alane-executable-examples/examples/amazon_provider_ec2_advance/test/fixtures/wrapper/configuration.tf

You could use a similar approach to add additional configuration before invoking the module that you want to test.
