### ISSUE TITLE
Interrupt received Kitchen::ActionFailed on kitchen test or kitchen converge

### ISSUE THREAD

**Issue by ibata** [newcontext-oss/kitchen-terraform#206]
Hi,
My goal is to test our terraform configuration using kitchen terraform. I did follow your instructions from http://www.rubydoc.info/gems/kitchen-terraform .

I am getting this error "Interrupt received Kitchen::ActionFailed" after running "kitchen test" on our long running terraform (35mn). Our "terraform apply" works fine and runs in 35mn because we have over 20 modules. I'm only testing one module here.

Running "terraform apply" always works but running "kitchen test" has failed consistently even when I choose one module only.

My colleague  noticed that running "kitchen converge" instead of "kitchen test"  worked but it  failed the next day with the same error "Interrupt received Kitchen::ActionFailed".

We were suspecting a time wait issue if there are too many modules. But we are just running one module.

I also noticed that there are not many internet articles about this error.
Here is the error:

       null_resource.start-mysql (remote-exec): Connected!
       null_resource.start-mysql (remote-exec): command: sudo /usr/sbin/mysqld --initialize-insecure --user=mysql
       null_resource.start-mysql: Still creating... (10s elapsed)
       null_resource.start-mysql: Still creating... (20s elapsed)
       null_resource.start-mysql: Still creating... (30s elapsed)
       Interrupt received.
       Please wait for Terraform to exit or data loss may occur.
       Gracefully shutting down...
       stopping apply operation...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <kt-suite-terraform>.  Please see .kitchen/logs/kt-suite-terraform.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

real	12m9.799s
user	0m29.247s
sys	0m8.796s

Please help because

**Comment by ncs-alane** [comment]
Hi @ibata: thank you for your interest in the project! 

I'm sorry that you're having a frustrating experience. I'll try to help you solve this problem.

Can you provide the output of `kitchen diagnose --all` so that we can see the resolved Test Kitchen configuration?

Just to clarify some Test Kitchen behaviour, the difference between `kitchen converge` and `kitchen test` is that `kitchen converge` runs `create` and `converge`, while `kitchen test` runs `destroy`, `create`, `converge`, `verify`, `destroy`. It looks like the error that you are experiencing is happening during the converge action which means that the choice of Test Kitchen command should not be important.

**Comment by ibata** [comment]
i just run "kitchen test" so that I can share the most recent "kitchen diagnose --all".

Lucs-MacBook-Pro:tf_popidol libata$ kitchen diagnose --all
$$$$$$ Running command `terraform version`
       Terraform v0.11.3
       + provider.aws v1.11.0
       + provider.chef v0.1.0
       + provider.null v1.0.0
       + provider.random v1.1.0
       + provider.template v1.0.0

       Your version of Terraform is out of date! The latest version
       is 0.11.4. You can update by downloading from www.terraform.io/downloads.html
$$$$$$ Terraform v0.11.3 is supported
---
timestamp: 2018-03-20 05:32:03 UTC
kitchen_version: 1.20.0
plugins:
  driver:
    Terraform:
      class: Kitchen::Driver::Terraform
      version: 3.1.0
      api_version: 2
  provisioner:
    Terraform:
      class: Kitchen::Provisioner::Terraform
      version: 3.1.0
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.20.0
      api_version: 1
  verifier:
    Terraform:
      class: Kitchen::Verifier::Terraform
      version: 3.1.0
      api_version: 2
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/Users/libata/source/tf_popidol/.kitchen.yml"
    raw_data:
      driver:
        name: terraform
        root_module_directory: "/Users/libata/source/tf_popidol"
        variable_files:
        - lucibatademotest.tfvars
      provisioner:
        name: terraform
      transport:
        name: ssh
        ssh_key: "/??????"
      verifier:
        name: terraform
        sudo: false
      platforms:
      - name: terraform
      suites:
      - name: kt_suite
        verifier:
          groups:
          - name: local
            controls:
            - inspec_attributes
          - name: remote
            controls:
            - reach_host
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: terraform
        root_module_directory: "/Users/libata/source/tf_popidol"
        variable_files:
        - lucibatademotest.tfvars
      provisioner:
        name: terraform
      transport:
        name: ssh
        ssh_key: "/???????"
      verifier:
        name: terraform
        sudo: false
      platforms:
      - name: terraform
      suites:
      - name: kt_suite
        verifier:
          groups:
          - name: local
            controls:
            - inspec_attributes
          - name: remote
            controls:
            - reach_host
instances:
  kt-suite-terraform:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      last_action: create
      last_error: Kitchen::ActionFailed
    driver:
      backend_configurations: {}
      color: true
      command_timeout: 600
      kitchen_root: "/Users/libata/source/tf_popidol"
      lock_timeout: 0
      log_level: :info
      name: terraform
      parallelism: 10
      plugin_directory:
      pre_create_command:
      root_module_directory: "/Users/libata/source/tf_popidol"
      test_base_path: "/Users/libata/source/tf_popidol/test/integration"
      variable_files:
      - "/Users/libata/source/tf_popidol/lucibatademotest.tfvars"
      variables: {}
    provisioner:
      command_prefix:
      debug:
      downloads: {}
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: "/Users/libata/source/tf_popidol"
      max_retries: 1
      name: terraform
      retry_on_exit_code: []
      root_path: "/tmp/kitchen"
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/Users/libata/source/tf_popidol/test/integration"
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/Users/libata/source/tf_popidol"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_http_proxy:
      ssh_http_proxy_password:
      ssh_http_proxy_port:
      ssh_http_proxy_user:
      ssh_key: "/???????"
      test_base_path: "/Users/libata/source/tf_popidol/test/integration"
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      color: true
      command_prefix:
      debug:
      ftp_proxy:
      groups:
      - name: local
        controls:
        - inspec_attributes
      - name: remote
        controls:
        - reach_host
      http_proxy:
      https_proxy:
      inspec_tests: []
      kitchen_root: "/Users/libata/source/tf_popidol"
      log_level: :info
      name: terraform
      root_path: "/tmp/verifier"
      sudo: false
      sudo_command: sudo -E
      suite_name: kt_suite
      test_base_path: "/Users/libata/source/tf_popidol/test/integration"

HERE IS THE ERROR:

       module.mysql.aws_instance.anastance: Still creating... (7m30s elapsed)
       module.mysql.aws_instance.anastance: Still creating... (7m40s elapsed)
       module.mysql.aws_instance.anastance: Still creating... (7m50s elapsed)
       module.mysql.aws_instance.anastance: Still creating... (8m0s elapsed)
       module.mysql.aws_instance.anastance: Still creating... (8m10s elapsed)
       Interrupt received.
       Please wait for Terraform to exit or data loss may occur.
       Gracefully shutting down...
       stopping apply operation...
       module.mysql.aws_instance.anastance: Creation complete after 8m18s (ID: i-0cc1a95f5ea6ea7fc)

       Outputs:

       environment = lucibatademotest4
       frontdoor = N/A
       launchpad = N/A
       password = <sensitive>
       speakeasy = N/A
       username = anaplan.customer@anaplan.com
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <kt-suite-terraform>.  Please see .kitchen/logs/kt-suite-terraform.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration


real	12m57.693s
user	1m47.229s
sys	0m23.907s

**Comment by ncs-alane** [comment]
@ibata I believe that this issue being caused by the driver configuration `command_timeout: 600`. That configuration means that any command executed by Kitchen-Terraform will be limited to 600 seconds of execution time. Can you try increasing that value to 2400?

**Comment by ibata** [comment]
I am going to try that.

**Comment by ibata** [comment]
Do you mean editing timeout from .kitchen.yml ? 
because I can not find where we have command_timeout:600. It seems like it's a driver built in - http://www.rubydoc.info/gems/kitchen-terraform/Kitchen/Terraform/ConfigAttribute/CommandTimeout

.kitchen.yml 
driver:
  name: terraform
  command_timeout: 2400
  variable_files:
    - xxxxx.tfvars

provisioner:
  name: terraform

**Comment by ncs-alane** [comment]
@ibata: I'm glad we were able to solve your original issue!

This new issue that you've shared appears to be caused by the provisioner of a null_resource in your Terraform configuration, which is beyond the scope of Kitchen-Terraform. It appears that the unf_ext gem is not installed in the Ruby environment of that provisioner, but I think that a Terraform or Chef forum would be a more appropriate place to attempt to diagnose this new issue.

**Comment by ibata** [comment]
@ncs-alane yes i'm using chefdk (chef ).  i'm going to close this issue and look for help for the other error unf_ext . Thanks for helping resolving it.
