### ISSUE TITLE
Kitchen UserError  Running command resulted in failure: No such file or directory - terraform

### ISSUE THREAD

**Issue by ibata** [newcontext-oss/kitchen-terraform#210]
In my quest to make kitchen terraform work. I decided to setup another instance with kitchen-terraform gems.

Getting this error After running "kitchen test" or "kitchen list" or "kitchen create". Looks like it can not find terrafom?

+ kitchen create
-----> Starting Kitchen (v1.19.2)
$$$$$$ Running command `terraform version`
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Running command resulted in failure: No such file or directory - terraform

Logs
vi .kitchen/logs/kitchen.log

E, [2018-03-22T20:41:14.103051 #21207] ERROR -- Kitchen: Class: Kitchen::Terraform::Error
E, [2018-03-22T20:41:14.103063 #21207] ERROR -- Kitchen: Message: Running command resulted in failure: No such file or directory - terraform
E, [2018-03-22T20:41:14.103076 #21207] ERROR -- Kitchen: ----------------------
E, [2018-03-22T20:41:14.103088 #21207] ERROR -- Kitchen: ------Backtrace-------
E, [2018-03-22T20:41:14.103111 #21207] ERROR -- Kitchen: /var/lib/jenkins/.chefdk/gem/ruby/2.4.0/gems/kitchen-terraform-3.2.0/lib/kitchen/driver/terraform.rb:269:in `rescue in verify_dependencies'
E, [2018-03-22T20:41:14.103124 #21207] ERROR -- Kitchen: /var/lib/jenkins/.chefdk/gem/ruby/2.4.0/gems/kitchen-terraform-3.2.0/lib/kitchen/driver/terraform.rb:255:in `verify_dependencies'
E, [2018-03-22T20:41:14.103137 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/driver.rb:43:in `for_plugin'
E, [2018-03-22T20:41:14.103152 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/config.rb:234:in `new_driver'
E, [2018-03-22T20:41:14.103172 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/config.rb:247:in `new_instance'
E, [2018-03-22T20:41:14.103186 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/config.rb:142:in `block in build_instances'
E, [2018-03-22T20:41:14.103198 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/config.rb:141:in `map'
E, [2018-03-22T20:41:14.103211 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/config.rb:141:in `with_index'
E, [2018-03-22T20:41:14.103233 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/config.rb:141:in `build_instances'
E, [2018-03-22T20:41:14.103246 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/config.rb:117:in `instances'
E, [2018-03-22T20:41:14.103259 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:112:in `filtered_instances'
E, [2018-03-22T20:41:14.103285 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:142:in `parse_subcommand'
E, [2018-03-22T20:41:14.103298 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/test.rb:40:in `block in call'
E, [2018-03-22T20:41:14.103310 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2018-03-22T20:41:14.103326 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/test.rb:38:in `call'
E, [2018-03-22T20:41:14.103339 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:52:in `perform'
E, [2018-03-22T20:41:14.103351 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:245:in `test'
E, [2018-03-22T20:41:14.103363 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2018-03-22T20:41:14.103380 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2018-03-22T20:41:14.103393 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2018-03-22T20:41:14.103406 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2018-03-22T20:41:14.103418 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `block in <top (required)>'
E, [2018-03-22T20:41:14.103431 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2018-03-22T20:41:14.103446 #21207] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `<top (required)>'
E, [2018-03-22T20:41:14.103459 #21207] ERROR -- Kitchen: /usr/bin/kitchen:255:in `load'
E, [2018-03-22T20:41:14.103482 #21207] ERROR -- Kitchen: /usr/bin/kitchen:255:in `<main>'
E, [2018-03-22T20:41:14.103495 #21207] ERROR -- Kitchen: ----End Backtrace-----

**Comment by ncs-alane** [comment]
Hello again @ibata!

As stated in the [driver documentation](http://www.rubydoc.info/github/newcontext-oss/kitchen-terraform/Kitchen/Driver/Terraform), the Terraform command-line interface is assumed to be present in the PATH of the user executing Test Kitchen. Can you try adding the path to `terraform` to your PATH and then executing Test Kitchen again?

**Comment by ibata** [comment]
@ncs-alane 
Same error after adding to PATH.
export PATH=$PATH:/opt/terraform

I am going to try to add terraform path to my .kitchen.yml at the driver section
plugin_directory: /path/to/terraform/plugins
plugin_directory: /opt/terraform

$ echo $PATH | tr ":" "\n" | nl
     1	/home/ubuntu/bin
     2	/home/ubuntu/.local/bin
     3	/home/ubuntu/.nvm/versions/node/v0.12.18/bin
     4	/usr/local/sbin
     5	/usr/local/bin
     6	/usr/sbin
     7	/usr/bin
     8	/sbin
     9	/bin
    10	/usr/games
    11	/usr/local/games
    12	/snap/bin
    13	/usr/lib/jvm/java-8-oracle/bin
    14	/usr/lib/jvm/java-8-oracle/db/bin
    15	/usr/lib/jvm/java-8-oracle/jre/bin
    16	/opt/terraform
    17	/opt

**Comment by ibata** [comment]
@ncs-alane same error after adding in path:
export PATH=$PATH:/opt/terraform

+ echo /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/opt/terraform

**Comment by ncs-alane** [comment]
@ibata can you share the output of `which terraform`?

**Comment by ncs-alane** [comment]
Related to #120

**Comment by ibata** [comment]
@ncs-alane no output after running "which terraform". By the way I'm using chefdk with my terraform and test-kitchen installation. and installed some of the gems using chef exec gem XXX

i'm going to fix the which terraform.

**Comment by ibata** [comment]
i reinstalled terraform and it's  fixed. 
   wget https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
   unzip terraform_0.11.3_linux_amd64.zip
   sudo mv terraform /usr/local/bin/
   ls  /usr/local/bin

**Comment by Paul1987** [comment]
I had the same problem; I could invoke the terraform application from the command line, but I was getting no response from `which terraform`. I re-installed it and manually added the binary to my path, and that seemed to resolve it.
