### ISSUE TITLE
Implement `kitchen doctor` action

### ISSUE THREAD

**Issue by ncs-alane** [newcontext-oss/kitchen-terraform#212]
The `doctor` action is intended to report to the user any issues in the test system and any issues in the Test Kitchen configuration.

Implementation in Kitchen::Configurable: https://github.com/test-kitchen/test-kitchen/blob/v3.5.0/lib/kitchen/configurable.rb#L50

`#doctor` must be implemented on each plugin.

Implementation in base provisioner: https://github.com/test-kitchen/test-kitchen/blob/v3.5.0/lib/kitchen/provisioner/base.rb#L108

Example of extended implementation in Chef base provisioner: https://github.com/test-kitchen/test-kitchen/blob/v3.5.0/lib/kitchen/provisioner/chef_base.rb#L246

**Comment by aaron-lane** [comment]
An empty `systems` array should be detected.

**Comment by aaron-lane** [comment]
Possibly integrate `inspec check`, `terraform validate`.

**Comment by aaron-lane** [comment]
A non-existent or non-executable `client` should be detected.

**Comment by aaron-lane** [comment]
Missing plugins should be detected.
