### ISSUE TITLE
Implement `kitchen package` command

### ISSUE THREAD

**Issue by ncs-alane** [newcontext-oss/kitchen-terraform#213]
The `package` action is intended to package a Test Kitchen instance. For Kitchen-Terraform, that may involve running `terraform graph` and `terraform fmt`.

The driver must implement `#package`.

Implementation in base driver: https://github.com/test-kitchen/test-kitchen/blob/v1.20.0/lib/kitchen/driver/base.rb#L61

**Comment by aaron-lane** [comment]
Closing as out of scope for the project.
