### ISSUE TITLE
how to testing multiple dynamic nodes from inspec test file

### ISSUE THREAD

**Issue by ibata** [newcontext-oss/kitchen-terraform#216]
Hi,

I'm spinning up multiple nodes that I need to test by doing the following for instance.

    describe command("curl -sS http://node-A") do
      its('stdout') { should_not match /HTTP Status 404/i }
      its('stderr') { should eq ''}
    end
    describe command("curl -sS http://node-B") do
      its('stdout') { should_not match /HTTP Status 404/i }
      its('stderr') { should eq ''}
    end

I want to be able to reach those nodes and run some curl command against them. 

I followed instructions from - https://github.com/newcontext-oss/kitchen-terraform/blob/master/examples/extensive_kitchen_terraform/test/integration/extensive_suite/controls/reachable_other_host.rb

which is about using the output.tf to pass information to the inspec test file.

it was failing on aws_ec2_instance. Saying that it is not recognized. I'm using chefdk and not using bundle install after I Gemfile edited. not sure if I have to use "chef exec bundle install" but when I did that I get another  error that suggest to install  gem missing unf_ext -v '0.0.7.5' which already installed.

**Comment by ncs-alane** [comment]
Hi @ibata:

Please refer to the [Kitchen-Terraform Bundler Installation Instructions](https://github.com/newcontext-oss/kitchen-terraform#bundler) for the preferred approach to installing the gem. Kitchen-Terraform can now be used by invoking Test Kitchen with `bundle exec kitchen`.

If `aws_ec2_instance` is not recognized then InSpec 2 may not be installed. After following the installation instructions, execute `bundle update` to make sure that you have the latest versions of all dependencies installed.

It should be possible to use Kitchen-Terraform with the Chef Development Kit but this is not a supported use case.

Is the issue involving `unf_ext` the same as what you mentioned in https://github.com/newcontext-oss/kitchen-terraform/issues/206#issuecomment-375451694? If so, that is an issue specific to how the Terraform configuration that you are working with is invoking `knife`, which is not a problem that we can solve.

**Comment by ibata** [comment]
thanks
