### ISSUE TITLE
Implement support for the `pre_create_command` configuration attribute of the driver

### ISSUE THREAD

**Issue by ncs-alane** [newcontext-oss/kitchen-terraform#217]
The base driver has a `pre_create_command` configuration attribute which is intended to be an optional string containing a shell out command. If the attribute is configured then the command will be executed before the rest of the `create` logic.

To properly support this attribute, a schema needs to be defined for it and `#create` must begin by calling `super`.

https://github.com/test-kitchen/test-kitchen/blob/v1.20.0/lib/kitchen/driver/base.rb#L142

**Comment by aaron-lane** [comment]
Closed in favour of #300.
