### ISSUE TITLE
Client error, can't connect to 'ssh' backend: You must provide a value for 'host'.

### ISSUE THREAD

**Issue by wolfyy66** [newcontext-oss/kitchen-terraform#224]
Hi there,

I'm not sure if this is the best place to ask my question. Apologies upfront in case it's not and please feel free to point me in the right direction.

I have two virtual machines under vbox : 
Linux server
Linux host

I have Inspec 'n the server and I'm trying to execute a script on the host using SSH
The thing is that when I use the : inspec shell -t ssh:/root@IP:PORT

All I have is this error : Client error, can't connect to 'ssh' backend: You must provide a value for 'host'.

Am I using the right command ?

**Comment by ncs-alane** [comment]
Hi @wolfyy66!

I believe that you are looking for the [InSpec repository](https://github.com/chef/inspec).
