### ISSUE TITLE
Question regarding using junit output with awspec with kitchen-terraform

### ISSUE THREAD

**Issue by twllight** [newcontext-oss/kitchen-terraform#246]
Helllo,
I have been slowly migrating our infrastructure tests to kitchen-terraform and its absolutely fabulous! So thank you for your hard work. I have a question regarding getting junit formatting to work however. This definitely may be due to my lack of ruby experience and if that is the case I apologize for the noob comment! 

I have setup my kitchen.yml as follows:
```
-bash-4.2$ cat .kitchen.yml
driver:
  name: terraform
  backend_configurations:
    region:     "us-east-1"
    bucket:     "<<snip>>"
    key:        "<<snip>>"
    lock_table: "<<snip>>"
  variable_files:
    - "../variables/terraform.tfvars.json"

provisioner:
  name: terraform
  directory: <<snip>>
  variable_files:
    - ../variables/terraform.tfvars.json

platforms:
  - name: centos

transport:
  name: ssh
  ssh_key: <<snip>>

verifier:
  name: awspec
  format: RspecJunitFormatter
  output: ./awspec_output.xml

suites:
    - name: consul-specs
      verifier:
        default_pattern: true
```
When running tests, tests are outputted to stdout in correct junit format. However, no xml file is written at all, as i would assume would be due to the output: key.

my rspec command runs and shows the correct formater 
```
12:51:02 kitchen-terraform_1  |        Running Awspec
12:51:02 kitchen-terraform_1  |        Using default pattern /tmp/terraform/backend-infrastructure/consul/spec/*_spec.rb
12:51:02 kitchen-terraform_1  |        Running command: rspec -c -f RspecJunitFormatter --default-path  /tmp/terraform/backend-infrastructure/consul  -P /tmp/terraform/backend-infrastructure/consul/spec/*_spec.rb
12:51:04 kitchen-terraform_1  | /tmp/terraform/backend-infrastructure/consul
```

If this is the wrong place i'll be happy to close. thank you for taking the time to have a look!

**Comment by ncs-alane** [comment]
Hi @twllight: thank you for your interest in the project! I believe that your question would be better posed at the repository for Kitchen::Verifier::Awspec: https://github.com/neillturner/kitchen-verifier-awspec.

Please note that Kitchen-Terraform does provide its own verifier plugin which provides better integration with the Terraform state and can still utilize awspec for testing AWS resources.

**Comment by twllight** [comment]
Thank you so much @ncs-alane I'll close here and move the issue over! thanks for the help
