### ISSUE TITLE
ProxyCommand not working

### ISSUE THREAD

**Issue by finferflu** [newcontext-oss/kitchen-terraform#251]
As documented in this [issue](https://github.com/newcontext-oss/kitchen-terraform/issues/50), Kitchen Terraform should be able to read the local `~/.ssh/config` file and connect to the host specified in that file. In my case, I have this in my `~/.ssh/config` file:

```sh
Host webinstance
  User test
  HostName <webinstance IP>
  ProxyCommand ssh -q test@<bastion IP> -W %h:%p
  IdentityFile ~/secret.key
```

I can connect just fine via command line.

In my `.kitchen.yml`, I have:

```yml
verifier:
  name: terraform
  groups:
    - name: default
      controls:
        - remote_exec
      hostnames: webinstance
```

When I run `bundle exec kitchen verify`, I get this error:

```
Message: Enumeration of groups and hostnames resulted in failure due to the omission of the configured :hostnames output or an unexpected output structure: key not found: "webinstance"
```

Am I doing anything wrong?

Thank you.

**Comment by edwardbartholomew** [comment]
Hi @finferflu Thank you for your interest in the project!

In this case, kitchen-terraform is expecting an output named webinstance that would contain the IP of the server you want to run tests on. Are you creating webinstance in your terraform module or does it already exist?

**Comment by finferflu** [comment]
Hi @edwardbartholomew, thank you very much for the speedy reply!

Your answer makes a lot of sense. The webinstance EC2 instance is part of an autoscaling group, and as such, Terraform has no way of knowing anything about the instance itself. I normally extrapolate the instance's IP or hostname via `awscli`, however since the output has to come from Terraform itself, I don't think I can rely on that method. As far as I understand even if I use a `local-exec` provisioner in Terraform, Terraform is unable to capture its output. It looks like I'm stumped, unless there's another way to pass a literal hostname to Kitchen Test?

Thanks!

**Comment by edwardbartholomew** [comment]
You are right - terraform (and kitchen-terraform) won't have knowledge of instances that launched. I need to think more what I have done in past but I believe you should be update your test integration code call aws cli to retrieve. Your ~/.ssh/config would then have the subnet range of your ASG like 10.10.20.* rather than "webinstance". I will try to see if I have any public examples of this anywhere.

**Comment by ncs-alane** [comment]
@finferflu One alternative would be to omit `hostnames` from the group, which causes the InSpec controls for that group to be executed on the local host, and then use the output of awscli in combination with InSpec command resources to make assertions about SSH commands run against the hosts in the autoscaling group.

**Comment by ncs-alane** [comment]
@finferflu: sorry for the delay in responding! The following is an example of what I am suggesting.

*kitchen.yml*
```yaml
verifier:
  name: terraform
  groups:
    - name: group_without_hostnames
      controls:
        - local_exec
```

*test/integration/<suite>/controls/some_control_file.rb*
```ruby
control "local_exec" do
  describe "an autoscaling host" do
    let :host_ip_address do
      command("awscli <command to obtain IP address>").stdout
    end

    it "should do a thing" do
      expect(command("ssh #{host_ip_address} <command to test>")).to match "some output"
    end
  end
end
```

**Comment by ncs-alane** [comment]
#247 introduced support for proxy configuration per verifier system!

**Comment by finferflu** [comment]
Thanks for the heads up, @ncs-alane, I can confirm that this works.
