### ISSUE TITLE
Add Sentinel Verifier Plugin

### ISSUE THREAD

**Issue by errygg** [newcontext-oss/kitchen-terraform#256]
Currently InSpec is the only supported verifier, but with the advent of [Sentinel Simulator](https://docs.hashicorp.com/sentinel/intro/getting-started/install) it would be great to add a second verifier to `kitchen-terraform` to support Sentinel policies as well as InSpec.

**Comment by ncs-alane** [comment]
Oh hello, @errygg!

 I like this idea. I think it can be incorporated in the v4 series of releases.

**Comment by errygg** [comment]
Hey @ncs-alane! Would love to help out on this too!

**Comment by aaron-lane** [comment]
@errygg do you have any ideas for how this would work? What would the workflow be?

**Comment by tbugfinder** [comment]
hm, would be OPA also a possible integration target?
https://www.openpolicyagent.org/docs/latest/terraform/
