### ISSUE TITLE
Getting undefined method when trying to use Awspec 

### ISSUE THREAD

**Issue by leonardo-test** [newcontext-oss/kitchen-terraform#257]
```
require "awspec"

control "file_check" do
  describe iam_user('my-iam-user') do
    it { should exist }
  end
end
```
```undefined method `iam_user' for #<#<Class:0x000000026deed8>:0x007f55c39108c8>```

Am I missing something here?

**Comment by ncs-alane** [comment]
Hi @leonardo-test. Thank you for your interest in the project!

As [awspec monkey patches RSpec::Core::ExampleGroup](https://github.com/k1LoW/awspec/blob/v1.7.0/lib/awspec/helper.rb), I believe you will need to introduce a second level of `describe` block to provide the correct context.

```ruby
require "awspec"

control "file_check" do
  describe "a thing" do
    describe iam_user('my-iam-user') do
      it { should exist }
    end
  end
end
```

**Comment by leonardo-test** [comment]
@ncs-alane Thanks for the quick response!

The second describe seems to have worked but is there a way to have it look at the aws instead of local?
```
Profile: default
Version: (not specified)
Target:  local://

  ∅  file_check: iam_user ''
     ∅  a thing iam_user '' should exist
     expected iam_user '' to exist

```

**Comment by ncs-alane** [comment]
Support for the new InSpec backends is coming with #247, but that should not matter for this case since you are using awspec, not native InSpec AWS resources. This latest failure appears to be caused by a misconfiguration of awspec.

**Comment by leonardo-test** [comment]
Is this configuration done in the .kitchen.yml ? I'm able to use awspec independently without any problems.

**Comment by leonardo-test** [comment]
I'm configuring the AWS credentials by editing the ~/.aws/config

**Comment by ncs-alane** [comment]
@leonardo-test are you able to share the project that you are working on?

**Comment by leonardo-test** [comment]
@ncs-alane Sorry but I just realised the iam user I was checking for doesn't actually exist. Looks like the check works. Thank you for everything!
