### ISSUE TITLE
Add Examples of InSpec AWS Backend and Kitchen Configuration

### ISSUE THREAD

**Issue by jaloren** [newcontext-oss/kitchen-terraform#263]
I recently upgraded from terraform kitchen 3.3 to kitchen 4.0. This meant that I could use inspec aws resources (which is great). However, I ran into some difficulties due to sparse documentation around how to use the aws backend and what one should put in the kitchen.yml. 

I'd like to submit a PR that adds documentation with this info. However, I am not sure the appropriate place for this doc. If someone could point me to a place, I'll whip up some markdown.

**Comment by jaloren** [comment]
@ncs-alane I have and that's very helpful but it didn't actually address the problem I had. So here's what the verifier documentation says about backends:

```
The value of the backend key is a scalar which is used to select the InSpec backend for connections to the system.

The scalar must match the name of one the available backends.
```

So then I went to the inspec backend url provided in the above documentation. That page only mentions this about backends:

```
-b, --backend=BACKEND
Choose a backend: local, ssh, winrm, docker.
```

Which led me to believe that only available backends for doing AWS resource testing was either local or SSH. Neither of those backends worked. I finally decided to attach pry debugger and trace through the code and discovered that the connection implementation is this gem:

https://www.rubydoc.info/gems/train/1.4.31/Train/Transports

And then I saw the AWS transport. Once I switched the backend to AWS, everything started working. Its this information about inspec backends and how that affects what inspec resources may use that would have been super helpful here.

**Comment by ncs-alane** [comment]
I agree that isn't very intuitive. I try to avoid duplicating documentation of the other systems associated with Kitchen-Terraform but it appears that some of the InSpec documentation has not been updated to reflect the latest features. The [Using InSpec 2.0 on Cloud Platforms](https://www.inspec.io/docs/reference/platforms/) article offers some more details, but it doesn't specifically acknowledge that the platforms being discussed are valid backends.

Do you think that a clarification that InSpec backends and platforms are the same thing and a link to the additional article is sufficient enough to provide guidance for other users?

**Comment by BensamV** [comment]
Kitchen Terraform Example for testing aws resources via backend aws
https://github.com/BensamV/kitchen-terraform-aws

**Comment by wyardley** [comment]
Similarly, I've had to do:
`bundle exec inspec exec -t gcp:// test/integration/default`

I have tried setting `backend: gcp` in both verifier and platforms => verifier, but can't seem to make it work. Is there a way to do this so that it runs terraform locally, but verifies using inspec's gcp provider?

**Comment by wyardley** [comment]
@aaron-lane: I think I tried that. I only have one “system” (that is, I’m not connecting to any systems or running any local tests; just verifying resources via the API, which I assume is “local” in the sense that it’s not doing remote execution). Also, those docs don’t list gcp or aws as valid options? Backend corresponds to the `-b` flag, so I’m not sure this will work for `-t gcp://`?

**Comment by aaron-lane** [comment]
@wyardley: My understanding is that InSpec's target flag is just a convenience wrapper which combines the backend flag, the user flag, the password flag, the host flag, and the port flag, so using it should not provide any different behaviour than specifying each of those flags separately, which is essentially what Kitchen-Terraform does. 

Based on the documentation of [inspec-gcp](https://github.com/inspec/inspec-gcp), the project has not yet been incorporated in to InSpec and must be explicitly included in the appropriate Inspec profile file before it will work.

Can you share the Kitchen configuration file of your project?
