### ISSUE TITLE
Unresolved gem dependencies with awspec >= 1.7.0 and kitchen-terraform 4.0

### ISSUE THREAD

**Issue by metmajer** [newcontext-oss/kitchen-terraform#269]
I wanted to give the new kitchen-terraform 4.0 a try and updated my Gemfile as follows:

```
source 'https://rubygems.org'
gem 'awspec', '~> 1.9.0'
gem 'kitchen-terraform', '~> 4.0'
gem 'kitchen-verifier-awspec', '~> 0.1'
gem 'hcl-checker', '~> 1.0.6'
gem 'inspec', '~> 2.2.78'
gem 'test-kitchen', '~> 1.23'
```

Running `bundle update` yields the following error:

```
❯ bundle update
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "aws-sdk":
  In Gemfile:
    awspec (~> 1.9.0) was resolved to 1.9.0, which depends on
      aws-sdk (~> 3)

    inspec (~> 2.2.78) was resolved to 2.2.78, which depends on
      train (>= 1.4.35, ~> 1.4) was resolved to 1.4.35, which depends on
        aws-sdk (~> 2)
```

I know that `kitchen-terraform` comes with support for InSpec backends, but I still need awspec working for now. Is there any way to continue to run `awspec` with `kitchen-terraform` 4.0? Thanks!

**Comment by ncs-alane** [comment]
@metmajer awspec 0.88.2 should be compatible with Kitchen-Terraform 4 as [it depends on aws-sdk 2](https://github.com/k1LoW/awspec/blob/v0.88.2/awspec.gemspec#L25). I recognize that using awspec 0.88.2 is not ideal as it is almost a year old but it may be adequate until you can migrate to InSpec resources.

By the way, you may not need to pin test-kitchen and inspec in your Gemfile as Kitchen-Terraform already ensures compatible versions will be installed.

**Comment by metmajer** [comment]
Hmm... that works as a temporary workaround. Thanks so much for your help and your suggestion on the Gemfile!
