### ISSUE TITLE
Destroying an empty Terraform state can fail

### ISSUE THREAD

**Issue by llibicpep** [newcontext-oss/kitchen-terraform#271]
What mentioned in https://github.com/hashicorp/terraform/issues/17862 basically preventing a good portion of tf modules to being covered with integration testing using kitchen (due to `kitchen test` which you usually want to use in CI environment along with `--destroy=always` will try to do `terraform destroy` first when nothing exists yet). The issue was there for a while and do not seem to be having high priority on terraform side - I was wondering is there any easy workaround could be possible on the `kitchen-terraform` side.

**Comment by llibicpep** [comment]
I actually need verify to fail in CI for obvious reasons. I know it's doable with bash traps and etc - but I much prefer to leave lifecycle management for kitchen.

**Comment by ncs-alane** [comment]
Unfortunately, aside from setting environment variables which modify how Terraform behaves, I don't believe much can be done from the Kitchen plugin side to account for the destroy error. It could be very dubious to attempt to determine why Terraform failed to destroy and take an action accordingly.

**Comment by llibicpep** [comment]
I was actually thinking about a flag in `.kitchen.yml` that will allow to ignore `destroy` failures when it's the first `destroy` in the lifecycle before `converge`. And again I don't like my suggestion myself - it's a dirty hack which really should be fixed on terraform side, but it seems like taking too long for them...

**Comment by frimik** [comment]
Regardless of Terraform bug I think it should _only_ destroy **after**. Like in a **begin/rescue/ensure** - attempt a destroy after regardless if successful test or not.

The pre-destroy scenario should be explicitly asked for. It should be up to the "CI" or operator to ensure the environment is clean imo.

If an infra is present before a run, something is obviously wrong. Or you have multiple test runs step on eachother. Or you named your resources something identical to something which happen to already exist in your environment, whatever that may be.

Run *B* should not care what run *A* (possibly) did. Run *B* should only clean up what run *B* did.

Allow an option for *keeping* the infra after a test failure (or success). for possible manual debug scenarios.

* Won't this create a multitude of terraform resources that never gets cleaned up if the **finally** cleanup stage fails over and over?

Sure, if you make every single resource random, it could. But that can be avoided by including a "unique" resource id/name which ensures you have a "semaphore" lock for ensure one single test run at a time. That still shouldn't be up to this tool to ensure.

**Comment by llibicpep** [comment]
@frimik what you said has nothing to do with `kitchen-terraform`. See https://docs.chef.io/ctl_kitchen.html#kitchen-test the `test` command is essentially a shortcut to perform destroy->converge->verify->destroy. You can use individual commands if you pleased to do so.

**Comment by frimik** [comment]
@llibicpep yes you're absolutely right. Thanks.

**Comment by aaron-lane** [comment]
@frimik: 

Thank you for your interest in the project!

Just to pick up on one thing you said:
> Allow an option for keeping the infra after a test failure (or success). for possible manual debug scenarios.

`kitchen test` will not run `terraform destroy` a second time unless the tests pass successfully. You can set the option `--destroy=always` to override this behaviour.

@llibicpep:

I propose that we close out this issue by documenting that the Terraform bug can disrupt the `kitchen test` workflow along with suggestions for working around it.
