### ISSUE TITLE
inspec version `2.2.101` breaks loading attributes from test module outputs

### ISSUE THREAD

**Issue by atheiman** [newcontext-oss/kitchen-terraform#274]
inspec version `2.2.101` seems to break our kitchen terraform tests. Something with attributes cannot be loaded from test module outputs

```
>>>>>>     Failed to complete #verify action: [Profile 'tests from {:path=>".some-terraform-module.test.integration.default"}' does not have a attribute with name 'some_output'] on default-test
```

The inspec code that raises this error: https://github.com/inspec/inspec/blob/master/lib/inspec/attribute_registry.rb#L54

Pull request that changed this just a couple days ago: https://github.com/inspec/inspec/pull/3318

And that change was released today: https://rubygems.org/gems/inspec/versions/2.2.101

**Comment by ncs-alane** [comment]
This is the cause of #272.

inspec/inspec#3318 enhanced the implementation of attributes. Attributes must now be declared in InSpec profile files before they can be accessed. The sudden breakage on our end is a result of this being a breaking change shipped in a patch version. It appears that InSpec releases are no longer adhering to semantic versioning. The dependency on InSpec should be pinned at the patch version and only after release notes are reviewed. :expressionless:
