### ISSUE TITLE
Is possible to skip the "terraform output -json"?

### ISSUE THREAD

**Issue by NTHINGs** [newcontext-oss/kitchen-terraform#278]
Hi is possible to skip it? Because sensitive data it's being shown.

Thanks

**Comment by ncs-alane** [comment]
Hi @NTHINGs!

Are you interested in hiding the output of `terraform output` or skipping the command entirely?

**Comment by NTHINGs** [comment]
Hey @ncs-alane. The output, because I am running the tests in  a CI environment and some outputs like the access keys of storage accounts are being shown.

**Comment by ncs-alane** [comment]
It is not currently possible to disable the output from only that specific command, but you can run Kitchen with a warning logger which will omit the info messages:

```sh
kitchen test --log-level=warn
```

**Comment by NTHINGs** [comment]
Thanks I removed the access keys from the output and I used the CLI for getting them into the test case

**Comment by nictrix** [comment]
I ran into the same issue, I added `sensitive = true` to each output to hide the secrets.

https://www.terraform.io/docs/configuration/outputs.html#sensitive
