### ISSUE TITLE
Add support for Inspec v3

### ISSUE THREAD

**Issue by edmeister** [newcontext-oss/kitchen-terraform#294]
Hi, I'm pretty new to Test Kitchen, Inspec and Ruby in general. A whole new world of infrastructure testing is opening up. 

Is it already possible to use Inspec 3 with Kitchen-Terraform? To verify our VM's Amazon Linux 2, we would need to use the latest release of Inspec. Our tests are suffering from this bug: https://github.com/inspec/inspec/issues/3614.

**Comment by aaron-lane** [comment]
Hi @edmeister! Thank you for your interest in the project.

Implementing support for InSpec 3 is the next priority for Kitchen-Terraform. I don't have an estimate on the delivery yet but I expect to have at least triaged what will be involved by 2018-11-28. From what I do know about InSpec 3, I expect it will be a breaking change for Kitchen-Terraform.

Some day very soon, I'll publish the roadmap for the project that I've been carrying around in my head. 🐢

**Comment by edmeister** [comment]
Thanks for the update @aaron-lane. I'll definitey follow-up and give feedback on early releases.

**Comment by aaron-lane** [comment]
Hey @edmeister, please test the `aaron-lane/inspec-v3.0` branch.
