### ISSUE TITLE
Add support for Terraform v0.12

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#298]
Hi,
as terraform 0.12 is getting closer to its release, kitchen-terraform support for tf 0.12 would be beneficial to start with at day-1 after 0.12 release.
My kitchen-terraform is reporting that 0.11 release is required.

Thanks

**Comment by gbergere** [comment]
Hey @aaron-lane any update on this ?

**Comment by aaron-lane** [comment]
Hi @tbugfinder and @gbergere. I apologize for the delay in responding! No updates as of yet; I'm hesitant to devote my limited development time toward versions of Terraform which are not generally available. That being said, the driver does have a `verify_version` attribute which can be set to `false` to allow testing with unsupported versions of Terraform. If the interfaces of the various commands used by Kitchen-Terraform have not changed, it should work as is. I would appreciate if you can report back on any issues encountered!

**Comment by gbergere** [comment]
Hi @aaron-lane,

Sure, I understand ;) 
Thanks a lot for your answer, I’ll have a try and let you know is I see issues or not!

Thanks for all your efforts in this project !

**Comment by gbergere** [comment]
Hi @aaron-lane, 

I just ran test-kitchen with terraform `v0.12.0-rc1` and `verify_version: false`, everything worked ! 🎉 

I'll run some more tests and wait to have a stable release of `v0.12` to fully migrate on this new version but it looks promising.

Thank you for all your work @aaron-lane

**Comment by ziporah** [comment]
Terraform v0.12.0 has been released, any news on releasing a version which supports it default ?

**Comment by aaron-lane** [comment]
@ziporah: let's see what tomorrow holds!
