### ISSUE TITLE
Extract Terraform CLI interactions to transport plugin

### ISSUE THREAD

**Issue by aaron-lane** [newcontext-oss/kitchen-terraform#299]
# Functions

It will:

* handle Terraform CLI interactions

# Objectives

It should:

* optionally verify support for the Terraform CLI version
* ensure the path to the Terraform CLI is valid (fixes #120)

# Constraints

It must:

* implement the existing workflow provided by the driver

**Comment by robbwagoner** [comment]
This should also support the `cli` attribute/key to allow use of Terraform wrappers like Terragrunt (since it is no longer supported in the Terraform driver).

**Comment by aaron-lane** [comment]
Fixed by #500. @robbwagoner that behaviour is still supported by the `client` attribute.
