### ISSUE TITLE
Add configuration attribute to `systems` which enables obtaining bastion host from Terraform output

### ISSUE THREAD

**Issue by gbergere** [newcontext-oss/kitchen-terraform#301]
Hello @aaron-lane, 

May I ask if there is a way to extract the `bastion_host` value from terraform outputs? The idea is to test a module which have instance in private subnets and be able to test it from scratch.

So the idea would be that terraform create (vpc, subnets, instances, ...) a bastion host in the public subnet used to reach instance in private subnet, test it then destroy everything.

I'm going to try to use it in here https://github.com/gbergere/tf-vpc-module/pull/11 where I want now to create private subnets in my VPC module and make my current kitchen tests able to keep running.

Thanks for you help
Geoffrey

**Comment by aaron-lane** [comment]
Hi @gbergere!

Thank you for your interest in the project.

Presently, you could populate `bastion_host` with an output value by leveraging the support for templating in the Kitchen configuration file. Below is an example of what that may look like.

```yaml
bastion_host: <%= `terraform output -state=<path to state file> -no-color <name of output>` %>
```

It's certainly not convenient, so we'll track this as a feature request to add an attribute like `bastion_host_output`.

**Comment by gbergere** [comment]
Looks like a nice trick, but after testing it, the command seems to be executed before running `terraform  apply` so terraform output is returning nothing. Isn't it?

**Comment by aaron-lane** [comment]
@gbergere true; you will need to explicitly run `kitchen converge` and then `kitchen verify` in order for this approach to correctly populate `bastion_host`.

**Comment by gbergere** [comment]
Thanks for the help, looking forward to see the feature added. Let me know if you need help.
If it's not too complicated I might be keen to PR this. @aaron-lane What do you think? 
Never really wrote code in Ruby but I guess most of the code is already written for `hosts_output` so it pretty much a simply copy/paste?

What would you reckon?

**Comment by aaron-lane** [comment]
@gbergere community contributions are always welcome! My recommendation would be to start by updating the specs which relate to `bastion_host`. There will certainly be similarities with the implementation of the `hosts_output` attribute.
