### ISSUE TITLE
save `terraform output` json file to inspec folder

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#310]
### Current behaviour
Current implementation provides terraform json output as attributes to inspec tests. This makes inspec tests dependent on kitchen-terraform attributes injection into inspec.
 
### Expected behaviour
Kitchen terraform should write the `terraform output -json` file to the inspec test/verify/files directory (?). That file could be loaded into inspec using e.g. `inspec.profile.file("terraform.json")` [ref](https://lollyrock.com/posts/inspec-terraform/)

Such a change makes tests more generic meaning that inspec tests could be written without a specific dependancy to the current output->attributes implementation.

**Comment by mattbowes** [comment]
Was there ever an update to address this? Is there way to get the terraform output as json to inspc?

**Comment by aaron-lane** [comment]
@mattbowes Kitchen has [lifecycle hooks](https://kitchen.ci/docs/reference/lifecycle-hooks/) which enable the execution of arbitrary scripts in between states of the test cycle. You could use the `pre_verify` hook to write the outputs to a file and read them in an InSpec control which uses the `local` backend.

**Comment by tbugfinder** [comment]
Meanwhile indeed I'm using a lifecycle hook in kitchen.yml
```
lifecycle:
  pre_verify:
  - local: ./lib/scripts/myoutputs.sh
```
Within myoutputs I'm also converting terraform output to yml preserving kitchen-terraform naming convention.
```
....
TOJFILE=/tmp/output.json
TOYFILE=/tmp/output.yml
TF_WORKSPACE=kitchen-terraform-${KITCHEN_INSTANCE_NAME} terraform output -json > "${TOJFILE}"
cat "${TFOFILE}" | jq 'with_entries(.value |= .value)|with_entries(.key = "output_" + .key)' | \
  ruby -ryaml -rjson -e 'puts YAML.dump(JSON.parse(STDIN.read, :symbolize_names => true))' > "${TOYFILE}"
```
