### ISSUE TITLE
provide support for WinRM verifier password calculator

### ISSUE THREAD

**Issue by lmayorga1980** [newcontext-oss/kitchen-terraform#317]
Seems like there is a need to calculate the windows password the same way the `kitchen-ec2` does when providing the ssl certificate key.

For instance in the following example(`kitchen-ec2`) I was able to let test-kitchen to retrieve the password based on the certificate.

https://github.com/LM3CORP/puppet-module-chrome/blob/master/.kitchen.yml#L30-L38

Maybe something like that can be done in this project to connect to windows hosts?

**Comment by aaron-lane** [comment]
We meet again, @lmayorga1980!

When using Kitchen-Terraform, connections to hosts are made through InSpec. The mappings of the Kitchen-Terraform verifier's [systems attribute](https://www.rubydoc.info/github/newcontext-oss/kitchen-terraform/Kitchen/Verifier/Terraform#label-systems) act as proxies for the [inspec exec](https://www.inspec.io/docs/reference/cli/#exec) command and should offer sufficient options to make connections using WinRM.

Are you able to share a project which fails to make a WinRM connection using a certificate?

**Comment by lmayorga1980** [comment]
You are right about the InSpec 

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [password is a required option] on default-ubuntu
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I was thinking on providing the key and let kitchen calculate the windows password

```ruby
    - name: nomad-clients
      backend: winrm
      ssh_key: ~/.ssh/lm3corp.pem
      port: 5986
      ssl: true
      winrm_transport: ssl
      self_signed: true
      controls:
        - chocopacks
      hosts_output: nomad_clients_dns
      user: Administrator
```

I think I used the following .kitchen.yml for a kitchen-ec2 and it was able to calculate the password based on the key.

```ruby
...
transport:
    name: winrm
    port: 5986
    ssh_key: ~/.ssh/test-kitchen.pem
    winrm_transport: ssl
    ssl: true
    connect_timeout: 60
    connection_retries: 5
    username: Administrator
```

**Comment by lmayorga1980** [comment]
I guess this decrypt password method is only available for `kitchen-ec2` gem but wondering if we can add it to this plugin.

https://github.com/test-kitchen/kitchen-ec2/blob/3fb421a6c6a26dc91235f25201a4e4f468b935e5/lib/kitchen/driver/ec2.rb#L555-L568

**Comment by aaron-lane** [comment]
@lmayorga1980:

I'm not familiar with WinRM. Can you help me to understand why the password needs to be derived from the certificate? I thought that the certificate would be used to authenticate the connection between InSpec and the Windows server.

**Comment by lmayorga1980** [comment]
The certificate needs to be used to decode the password in the case for ec2 instances. 

https://aws.amazon.com/premiumsupport/knowledge-center/retrieve-windows-admin-password/
https://docs.aws.amazon.com/cli/latest/reference/ec2/get-password-data.html

**Comment by lmayorga1980** [comment]
I think `kitchen-terraform` should be able to handle, depending on some cloud providers, a generic function that calculates the cloud-provider for windows and calculate the windows administrator password based on the certificate file path.

**Comment by aaron-lane** [comment]
Hey @lmayorga1980 👋🏼 

I'm looking at this again. I found that the logic relied on by Kitchen-EC2 ultimately comes from the AWS SDK for Ruby: https://github.com/aws/aws-sdk-ruby/blob/177763d7fba630c88f9c3ea41486d04b1727e309/gems/aws-sdk-ec2/lib/aws-sdk-ec2/customizations/instance.rb#L11-L16. It does seem quite straightforward to add. I think this request can be supported.
