### ISSUE TITLE
Automatically provide Terraform outputs as Inspec attributes

### ISSUE THREAD

**Issue by ncs-alane** [newcontext-oss/kitchen-terraform#32]
Since the user will likely be assigning the attribute value to a variable before using it, requiring the extra step of explicting mapping output names to attribute names seems frivolous.

**Comment by gbergere** [comment]
Hello @ncs-alane, any dos about how to use this ?

**Comment by ncs-alane** [comment]
@gbergere the detailed AWS provider example has a control that [demonstrates how the attribute and output mapping works](https://github.com/newcontext-oss/kitchen-terraform/blob/master/examples/aws_provider/test/integration/example/controls/remote_security_group.rb#L17-L18).
