### ISSUE TITLE
add support for backend.tfvars in double hop maybe

### ISSUE THREAD

**Issue by lmayorga1980** [newcontext-oss/kitchen-terraform#322]
When using a Consul Remote Backend Terraform does not support interpolation unless you use an approach described here.

https://www.monterail.com/blog/chicken-or-egg-terraforms-remote-backend

It would be nice to have under `kitchen-terraform`

**Comment by aaron-lane** [comment]
Hi @lmayorga1980!

I apologize for the very delayed response. I read your issue several weeks ago but was distracted before I could respond. 😞

The driver plugin [currently supports](https://www.rubydoc.info/github/newcontext-oss/kitchen-terraform/Kitchen/Driver/Terraform#label-backend_configurations) the key/value pair behaviour of `-backend-config`. Are you specifically interested in support for specifying a file path?
