### ISSUE TITLE
provider.aws: no suitable version installed

### ISSUE THREAD

**Issue by wilsonebo1** [newcontext-oss/kitchen-terraform#328]
I keep getting this error, I have no idea what it means ? or how to fix it 

Plugin reinitialization required. Please run "terraform init".                  
 Reason: Could not satisfy plugin requirements.                                                                                                                    Plugins are external binaries that Terraform uses to access and manipulate       resources. The configuration provided requires plugins which can't be located,   don't satisfy the version constraints, or are otherwise incompatible.                                                                                             1 error(s) occurred:                                                                                                                                              * provider.aws: no suitable version installed                                      version requirements: "(any version)"                                            versions installed: none                                                                                                                                        Terraform automatically discovers provider requirements from your                configuration, including providers used in child modules. To see the             requirements and constraints from each module, run "terraform providers".                                                                                                                                                                          Error: error satisfying plugin requirements
--

**Comment by aaron-lane** [comment]
Hi @wilsonebo1! Thank you for your interest in the project.

Unfortunately, we can not provide any assistance based on the information which you have provided. Can you please include more context, like the Terraform configuration, Kitchen configuration, and commands to reproduce this error?
