### ISSUE TITLE
Add support for terraforms "target" option

### ISSUE THREAD

**Issue by DanielChalk** [newcontext-oss/kitchen-terraform#337]
Some of my work involves using glue modules which use other modules but unfortately terraforms dependency graph does't play well with modules depending on resources in other modules.

To mitigate this I propose we enable using the target option so we can apply portions of a terraform module as needed.

**Comment by aaron-lane** [comment]
Hi @DanielChalk!

Thank you for your interest in the project. I apologize for the delay in responding.

Can you please provide some context about "glue modules"? I'm not clear on why one module would need to depend on the resources of a different module; that's what outputs are for.

**Comment by DanielChalk** [comment]
Hi @aaron-lane, I actually resolved my own problem, it wasn't a limitation in Kitchen Terraform at all but a new user failing to make sense of a new tool.
