### ISSUE TITLE
Add support for InSpec v4

### ISSUE THREAD

**Issue by croteaub** [newcontext-oss/kitchen-terraform#342]
In kitchen-terraform:

Attempting to use InSpec resources for GCP, specifically for checking for external IP.

After running the code, it creates in an error in the log file kt-suite-terraform.log:

[2019-05-20T12:24:56.341783 #54125] ERROR -- kt-suite-terraform: Class: Kitchen::Terraform::Error
E, [2019-05-20T12:24:56.341797 #54125] ERROR -- kt-suite-terraform: Message: external_ip: This profile requires InSpec version ~> 4.3. You are running InSpec v3.9.3.

My current config:

Ruby 2.4.1
Kitchen-terraform 4.8.1
inspec 4.3.2

terminal error message:

bundle exec kitchen verify
Bundler could not find compatible versions for gem "inspec":
  In Gemfile:
    inspec (~> 4.3, >= 4.3.2)

    kitchen-terraform (~> 4.8, >= 4.8.1) was resolved to 4.8.1, which depends on
      inspec (~> 3.0)

Could not find gem 'inspec (~> 3.0)', which is required by gem 'kitchen-terraform (~> 4.8, >= 4.8.1)', in any of the sources.

.kitchen.yml
`---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  parallelism: 4

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: external_ip
      backend: local
      controls:
        - external_address_exists

platforms:
  - name: terraform

suites:
  - name: kt_suite
`

inspec.yml
`
---

name: default
title: Terraform Testing Profile
summary: Verify that and external IP exists for the creation region
maintainer: xxxxxxxxxx
copyright: xxxxxxxxxx
license: Proprietary, All rights reserved
version: 0.1.0
supports:
  - platform-family: gcp
inspec_version: "~> 4.3"
`

**Comment by aaron-lane** [comment]
@croteaub: thank you for your interest in the project!

I apologize for the inconvenience. We can investigate updating the supported version of InSpec.

**Comment by aaron-lane** [comment]
@croteaub please test the `aaron-lane-inspec-4` branch if you are able.
