### ISSUE TITLE
Allow default workspace

### ISSUE THREAD

**Issue by marko7460** [newcontext-oss/kitchen-terraform#348]
kitchen-terraform creates `kitchen-terraform-<instance.name>` workspaces when running `kitchen create/converge`. Some customers have already deployed systems for which they would like to run/create tests. Those systems are almost always deployed in default workspace.
Would it be possible to enable a flag in `.kitchen.yml` that can allow running tests (`kitchen create/converge/verify`) against default workspace?

**Comment by aaron-lane** [comment]
Hey @marko7460! We should be able to accomodate that.

**Comment by vinisha1995** [comment]
yes, this is exactly what we want!!, we are already using a Terraform pipeline to deploy our systems and we want kitchen-Terraform tests to verify against it using the same backend which pipeline uses instead its creating its own workspace and backend and creating a completely new deployment. Is there any way to do this?

**Comment by aaron-lane** [comment]
Hi @vinisha1995! This is not currently supported but hopefully one of the maintainers can find time to implement it.
