### ISSUE TITLE
root_module_directory not validated for existence

### ISSUE THREAD

**Issue by red2k18** [newcontext-oss/kitchen-terraform#355]
Error says `can't connect to 'ssh' backend: SSH command failed` when match for `root_module_directory` value is not found.

**Comment by aaron-lane** [comment]
Hi @red2k18! Thank you for your interest in the project.

I agree that is not a great experience. This should be covered by #354.

**Comment by red2k18** [comment]
Awesome, thanks @aaron-lane!
