### ISSUE TITLE
AWS tutorial is out of date

### ISSUE THREAD

**Issue by mchassy** [newcontext-oss/kitchen-terraform#365]
I have been working through the AWS EC2 tutorial. (`https://newcontext-oss.github.io/kitchen-terraform/tutorials/amazon_provider_ec2.html`)

I am not getting any errors and the instances are created when I run `bundle exec kitchen verify`.

But when I run `bundle exec kitchen verify` the tests are not being executed.
I didn't even get the `0 examples, 0 failures` message when I don't have any tests to run.

![Screenshot 2019-09-30 at 16 47 13](https://user-images.githubusercontent.com/15926092/65894660-02a3b100-e3a2-11e9-8472-b22505f2bfd5.png)

I am also attaching a screenshot of the folder structure and the .kitchen.yml.
The terraform files are slightly different, but the work so I don't believe the problem is there.

![Screenshot 2019-09-30 at 16 38 37](https://user-images.githubusercontent.com/15926092/65894172-34684800-e3a1-11e9-9130-03ee39ff912a.png)

**Comment by mchassy** [comment]
After more research, it looks like your tutorials are completely out of date as they use `groups:` instead of `systems:`. It would be helpful to update your aws tutorial.

**Comment by aaron-lane** [comment]
Hi @mchassy! Thank you for your interest in the project. I apologize for the frustrating experience with the tutorial. Fixing out of date documentation is definitely a priority; it's just a matter of finding time to do it. :disappointed:

**Comment by mchassy** [comment]
Apology accepted ;-)
Just let me know when things are updated.

**Comment by edwardbartholomew** [comment]
I wonder if we need to maintain multiple versions of the tutorials for different kitchen-terraform versions or just update to the latest? Any thoughts @aaron-lane ?

**Comment by aaron-lane** [comment]
Fixed by #378.
