### ISSUE TITLE
Failing when aws config have web_identity_token_file

### ISSUE THREAD

**Issue by llibicpep** [newcontext-oss/kitchen-terraform#368]
I hope this is as simple as updating SDK version. For the following `~/.aws/config`:

```
[profile profile1]
role_arn = arn:aws:iam::xxx:role/role1
web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token
[profile profile2]
source_profile = profile1
role_arn = arn:aws:iam::xxx:role/role2
```

Getting the following error message:

```
     Profile target has a role_arn, and source_profile, but the source_profile does not have credentials.
```

The use case is to run kitchen tests in EKS pod that is using IAM attached via Service Account as explained here https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by aaron-lane** [comment]
Hi @llibicpep!

I apologize for not responding to this issue sooner. I think you're referring to the AWS SDK gems which are in the Kitchen-Terraform dependencies tree. If that is correct, those are transient dependencies which Kitchen-Terraform does not manage, but you should be able to update them with `bundle update`. Please reopen this issue if my suggestion does not solve the problem.
