### ISSUE TITLE
cinc support

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#370]
Hi,
the community effort for OSS chef tooling within [https://cinc.sh](https://cinc.sh) is making great progress. Cinc-auditor is the "free" version of Inspec.
I'm wondering if `kitchen-terraform` would support `cinc-auditor` as a pluggable replacement for Inpsec.
On the other hand Inspec Gem doesn't require a license/EULA as of today.

**Comment by aaron-lane** [comment]
@tbugfinder I think this is a reasonable request, but I haven't been following the Chef licensing situation closely. Is the InSpec gem slated to require acceptance of a license in the future?

**Comment by tbugfinder** [comment]
Well, documentation is slightly confusing to me.
Though, my understanding is that inspec-bin requires accpeting the Chef license https://docs.chef.io/chef_license_accept.html but inspec libs themselves are "free / Apache License, 2.0" and don't.

**Comment by tbugfinder** [comment]
Modules like `inspec-aws`, `inspec-azure` require inspec-bin, though. That's a little messy.....

**Comment by aaron-lane** [comment]
It may be worthwhile to request those gems to replace inspec-cli with inspec if possible.

**Comment by bobchaos** [comment]
https://github.com/inspec/inspec/pull/4971 The discussion in there explains what's the story with inspec-core. Inspec-bin shouldn't be an issue as you're not actually running it as I understand, it just gets pulled in automatically.

**Comment by tbugfinder** [comment]
Correct, loading libs is ok and profiles like inspec-aws are not loaded as gems.
Close it for now?
