### ISSUE TITLE
Add configuration attribute to verifier plugin which toggles fast failure behaviour

### ISSUE THREAD

**Issue by ncs-alane** [newcontext-oss/kitchen-terraform#38]
Currently, the verify action will stop on the first InSpec control failure of any verifier group, which is considered to be a fast failure. It would be valuable in scenarios like continuous integration testing to see the results of all of the controls rather than just the first failure, which would be considered to be a slow failure. This new configuration attribute will allow the user to toggle between fast failure and slow failure.

Name: fast_failure
Type: Boolean
Required: False
Default: `true`

**Comment by henrydobson** [comment]
@ncs-alane is there a way to fail-slow currently?

**Comment by henrydobson** [comment]
Fast-fail behaviour also prevents `kitchen test` from running the destroy.

**Comment by ncs-alane** [comment]
@henrydobson unfortunately not. This was deprioritized in favour of the v4.0.0 release, but now we can get this implemented.

Just to note, the ability to fail slowly will still not solve the problem of `kitchen test` failing to destroy a Kitchen instance when tests fail. In order to do that, you can use `kitchen test --destroy=always` (the default is `--destroy=passing`.
