### ISSUE TITLE
bundle exec kitchen verify <name> is greedy

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#380]
Hi,

I've defined two suites:
a) integration
b) integration-detailed

If `bundle exec kitchen verify integration` is invoked, both suites are run. However I'd expect that only a) is run.
If a) is renamed to integration-baseline, only that single suite is executed when `bundle exec kitchen verify integration-baseline` is invoked.

Version:
kitchen-terraform 5.1.1

Thanks and Best

**Comment by aaron-lane** [comment]
Hello again @tbugfinder! What you're describing is behaviour of [Kitchen](https://kitchen.io/). Kitchen performs fuzzy matching for instance arguments, so it's working as expected that "integration" matches both instances defined. Instances are the resulting combination of all suites and all platforms in the Kitchen configuration. You can use `kitchen list` to identify the fully qualified instance names if you want to test only a single instance.

**Comment by tbugfinder** [comment]
Hi @aaron-lane 
thanks for clarification.
