### ISSUE TITLE
kt don't like my inspec profile helpers

### ISSUE THREAD

**Issue by binamov** [newcontext-oss/kitchen-terraform#391]
This works fine:
`inspec exec https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark.git -t gcp://`

Doing this from kt in `.kitchen.yml` with
```
      profile_locations:
        - https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark.git
```

blows up on `verify` with:
```>>>>>> Verifying the 'system' system failed:
        Running InSpec failed:
        undefined method `get_gce_instances' for #<Inspec::ControlEvalContext:0x00007f42ca5d26b8>
Did you mean?  google_compute_instances
```

If I run `inspec exec` first, k-t `verify` seems to work just fine.

**Comment by aaron-lane** [comment]
This error is reproducible using the CLI with InSpec 4.18.97 and 4.18.100. A different error occurs with InSpec 4.18.85. This does not appear to be an issue with Kitchen-Terraform.

**Comment by aaron-lane** [comment]
Explicitly pinning InSpec in your `gems.rb` or `Gemfile` is a workaround while the underlying issue is identified:

```rb
gem "inspec", "4.18.51"
```

**Comment by aaron-lane** [comment]
This was determined to be an InSpec issue.
