### ISSUE TITLE
Rubydocs is in part not readable

### ISSUE THREAD

**Issue by ehaselwanter** [newcontext-oss/kitchen-terraform#393]
great doc. a few render issues at the moment:

- https://www.rubydoc.info/github/newcontext-oss/kitchen-terraform/Kitchen/Verifier/Terraform

![image](https://user-images.githubusercontent.com/18671/76509544-7a493200-6450-11ea-82f6-3303e1fc9693.png)

**Comment by aaron-lane** [comment]
Hi @ehaselwanter! The page you shared is rendering okay for me when viewed in Brave. :confused: Is the problem unique to a specific browser?

![Screenshot from 2020-03-12 09-52-00](https://user-images.githubusercontent.com/10655063/76528476-3f8ecc00-6447-11ea-8994-0c8f7748f6f4.png)

**Comment by ehaselwanter** [comment]
@aaron-lane I had the issue yesterday in Chrome and Safari on macOS .. maybe a transient issue. renders fine again.
