### ISSUE TITLE
I'm getting inconsistent results between a terraform apply locally and a terraform apply with kitchenCI

### ISSUE THREAD

**Issue by pswalia06** [newcontext-oss/kitchen-terraform#397]
1. my local results here: 
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # azurerm_subnet.main will be created
  + resource "azurerm_subnet" "main" {
      + address_prefix                                 = "10.240.1.0/24"
      + address_prefixes                               = (known after apply)
      + enforce_private_link_endpoint_network_policies = false
      + enforce_private_link_service_network_policies  = false
      + id                                             = (known after apply)
      + name                                           = "ab-sandbox-coa-cc-subnet"
      + resource_group_name                            = "ab-sandbox-coa-cc-rg"
      + virtual_network_name                           = "ab-sandbox-coa-cc-vnet"
    }

  # azurerm_virtual_network.example will be created
  + resource "azurerm_virtual_network" "example" {
      + address_space       = [
          + "10.240.0.0/16",
        ]
      + guid                = (known after apply)
      + id                  = (known after apply)
      + location            = "canadacentral"
      + name                = "ab-sandbox-coa-cc-vnet"
      + resource_group_name = "ab-sandbox-coa-cc-rg"
      + subnet              = (known after apply)
    }

  # module.aks_cluster.data.azurerm_subnet.main["aks_cluster"] will be read during apply
  # (config refers to values not yet known)
 <= data "azurerm_subnet" "main"  {
      + address_prefix                                 = (known after apply)
      + address_prefixes                               = (known after apply)
      + enforce_private_link_endpoint_network_policies = (known after apply)
      + enforce_private_link_service_network_policies  = (known after apply)
      + id                                             = (known after apply)
      + name                                           = "ab-sandbox-coa-cc-subnet"
      + network_security_group_id                      = (known after apply)
      + resource_group_name                            = "ab-sandbox-coa-cc-rg"
      + route_table_id                                 = (known after apply)
      + service_endpoints                              = (known after apply)
      + virtual_network_name                           = "ab-sandbox-coa-cc-vnet"

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.aks_cluster.azurerm_kubernetes_cluster.main["aks_cluster"] will be created
  + resource "azurerm_kubernetes_cluster" "main" {
      + dns_prefix              = "sandboxtestdns"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + kube_admin_config       = (known after apply)
      + kube_admin_config_raw   = (sensitive value)
      + kube_config             = (known after apply)
      + kube_config_raw         = (sensitive value)
      + kubelet_identity        = (known after apply)
      + kubernetes_version      = "1.14.8"
      + location                = "canadacentral"
      + name                    = "ab-sandbox-kubernetes-cc-aks"
      + node_resource_group     = "ab-sandbox-kubernetes-aks-cc-rg"
      + private_cluster_enabled = true
      + private_fqdn            = (known after apply)
      + private_link_enabled    = (known after apply)
      + resource_group_name     = "ab-sandbox-coa-cc-rg"

 

      + default_node_pool {
          + max_pods        = (known after apply)
          + name            = "standard"
          + node_count      = 2
          + os_disk_size_gb = 30
          + type            = "VirtualMachineScaleSets"
          + vm_size         = "Standard_D3_v2"
          + vnet_subnet_id  = (known after apply)
        }

      + identity {
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned"
        }

      + linux_profile {
          + admin_username = "ab"

          + ssh_key {
              + key_data = (known after apply)
            }
        }

      + network_profile {
          + dns_service_ip     = (known after apply)
          + docker_bridge_cidr = (known after apply)
          + load_balancer_sku  = "standard"
          + network_plugin     = "kubenet"
          + network_policy     = (known after apply)
          + outbound_type      = "loadBalancer"
          + pod_cidr           = (known after apply)
          + service_cidr       = (known after apply)

          + load_balancer_profile {
              + effective_outbound_ips    = (known after apply)
              + managed_outbound_ip_count = (known after apply)
              + outbound_ip_address_ids   = (known after apply)
              + outbound_ip_prefix_ids    = (known after apply)
            }
        }

      + role_based_access_control {
          + enabled = false
        }

      + windows_profile {
          + admin_password = (sensitive value)
          + admin_username = (known after apply)
        }
    }

  # module.aks_cluster.azurerm_private_endpoint.main["aks_cluster"] will be created
  + resource "azurerm_private_endpoint" "main" {
      + id                  = (known after apply)
      + location            = "canadacentral"
      + name                = "ab-sandbox-kubernetes-cc-aks"
      + resource_group_name = "ab-sandbox-coa-cc-rg"
      + subnet_id           = (known after apply)

      + private_service_connection {
          + is_manual_connection           = false
          + name                           = "ab-sandbox-kubernetes-cc-aks"
          + private_connection_resource_id = (known after apply)
          + private_ip_address             = (known after apply)
          + subresource_names              = [
              + "management",
            ]
        }
    }

  # module.aks_cluster.null_resource.main["aks_cluster"] will be created
  + resource "null_resource" "main" {
      + id       = (known after apply)
      + triggers = (known after apply)
    }

  # module.aks_cluster.null_resource.save-key will be created
  + resource "null_resource" "save-key" {
      + id       = (known after apply)
      + triggers = (known after apply)
    }

  # module.aks_cluster.tls_private_key.key will be created
  + resource "tls_private_key" "key" {
      + algorithm                  = "RSA"
      + ecdsa_curve                = "P224"
      + id                         = (known after apply)
      + private_key_pem            = (sensitive value)
      + public_key_fingerprint_md5 = (known after apply)
      + public_key_openssh         = (known after apply)
      + public_key_pem             = (known after apply)
      + rsa_bits                   = 2048
    }

Plan: 7 to add, 0 to change, 0 to destroy.

2. When running from Jenkins I am below error

      
       
       Error: Invalid for_each argument
       
         on ../../../../main.tf line 109, in resource "azurerm_private_endpoint" "main":
        109:   for_each            = local.aks

**Comment by aaron-lane** [comment]
Hi @pswalia06. Thank you for your interest in the project!

Unfortunately, the information you have provided does not seem to indicate any relevance to Kitchen-Terraform. Can you clarify why you think this error is caused by Kitchen-Terraform specifically?

**Comment by pswalia06** [comment]
@aaron-lane  
When I run  an apply it works locally with the same version of terraform but when I run with kitchen it produces an error.

**Comment by aaron-lane** [comment]
Can you provide more information about your Terraform confirmation and your Kitchen configuration? What is the definition of `local.aks`?

**Comment by dwizzle204** [comment]
Not sure if similar but i've also seen some weird difference between a local run and run initiated by kitchenci. Seems to only be related to the for_each calls.

Example
```
subnet = {
  subnet01 = {
      route_table =  "rt_tb01"
  }
}

data "azurerm_route_table" "main" {
  for_each            = { for y, x in var.subnet : y => x if lookup(x, "route_table", null) != null }
  name                = each.value["route_table"]
  resource_group_name = "some_rg_name"
}
```
Run natively with TF 12.20 this will work as intended but when run with kitchenci it produces this error

```
on ../../../../main.tf line 25, in data "azurerm_route_table" "main":

25: for_each = { for y, x in var.subnet : y => x if lookup(x, "route_table", null) != null }

The "for_each" value depends on resource attributes that cannot be determined

until apply, so Terraform cannot predict how many instances will be created.

To work around this, use the -target argument to first apply only the

resources that the for_each depends on.
```

**Comment by aaron-lane** [comment]
@dwizzle204 thank you for the additional context!

Could either of you please provide a repository which reproduces the issue? My theory is the issue stems from some sort of contextual inputs to the Terraform configurations. Kitchen-Terraform makes use of standard Terraform CLI commands when it executes which should narrow down issues like this to Terraform workspaces or variables.
