### ISSUE TITLE
The new version 0.5.4 is missing on rubygems.org

### ISSUE THREAD

**Issue by dbro86** [newcontext-oss/kitchen-terraform#402]
It would by fine if the new version 0.5.4 is available on rubygems.org.
Kind regards

**Comment by edwardbartholomew** [comment]
Greetings @dbro86 and thank you for your interesting in kitchen-terraform. We had issue with release job that pushes the gem to RubyGems and are currently working to migrate that job to GitHub Actions in #401  We hope to have that wrapped up this week.

**Comment by edwardbartholomew** [comment]
@dbro86 - Thanks for your patience - the latest version is now on rubygems.org. There is now a GitHub Actions job to push releases so hopefully won't be delay in future.
