### ISSUE TITLE
Add support for Terraform 0.13

### ISSUE THREAD

**Issue by justyns** [newcontext-oss/kitchen-terraform#412]
Terraform [0.13.0-rc1](https://github.com/hashicorp/terraform/releases/tag/v0.13.0-rc1) was released recently.  While it's not GA yet, it would be a good idea to start adding support for and testing 0.13.

**References:**
* https://github.com/hashicorp/terraform/blob/guide-v0.13-beta/draft-upgrade-guide.md
* https://github.com/hashicorp/terraform/releases/tag/v0.13.0-rc1
* https://www.hashicorp.com/blog/announcing-the-terraform-0-13-beta/

**Comment by aaron-lane** [comment]
Why hello there, @justyns!

It never hurts to be prepared. We can start testing 0.13-rc1 presently by configuring `driver.verify_version: false`.

**Comment by bharathkkb** [comment]
@aaron-lane 👋 this saved me alot of digging 😄

**Comment by aaron-lane** [comment]
Hello again @bharathkkb! Glad to hear that 😁

**Comment by edwardbartholomew** [comment]
Well looks like 0.13 has been released! For those of you using `driver.verify_version: false`, have you experienced any issues with your regular kitchen-terraform workflow or noticed any potential bugs?

**Comment by justyns** [comment]
@aaron-lane @edwardbartholomew 👋 

We've been migrating multiple modules from 0.11.x to 0.13.0-rc1 (and now 0.13.0), and so far haven't run into any issues with `driver.verify_version: false` that aren't related to just upgrading to 0.12.x in general.

**Comment by edwardbartholomew** [comment]
Thanks for the update @justyns ... I've started WIP PR for this https://github.com/newcontext-oss/kitchen-terraform/pull/414

**Comment by bharathkkb** [comment]
@edwardbartholomew same here, tested multiple modules for 0.13 compat and everything fine with `driver.verify_version: false`.

**Comment by edwardbartholomew** [comment]
Fixed by #414
