### ISSUE TITLE
Request support for iam_profile_name in .kitchen.yml

### ISSUE THREAD

**Issue by danwiltshire** [newcontext-oss/kitchen-terraform#422]
Hey,

I'd like to submit a feature request for supporting iam_profile_name in .kitchen.yml, similar to https://github.com/test-kitchen/kitchen-ec2.

This would be particularly useful for those using ~/.aws/config to setup different profiles for environments.

Currently this can be achived by exporting `AWS_PROFILE` however, if a different profile is used to converge the Kitchen environment, this has to be managed, e.g:

~/.aws/config
```config
[default]
region=eu-west-2

[profile kitchen-terraform-default-aws]
role_arn=arn:aws:iam::1234567890:role/terra_role
region=eu-west-2
source_profile=default
```

~/.aws/credentials
```config
[default]
aws_access_key_id=ABCDE
aws_secret_access_key=ABCDE
```

Terraform:
```hcl
provider "aws" {
  profile = terraform.workspace
  // Specify region because Terraform ignores region in ~/.aws/config
  region = var.aws_provider_configuration[terraform.workspace]["region"]
```

Test script:
```bash
bundler exec kitchen converge
export AWS_PROFILE=profile-name
bundler exec kitchen verify
unset AWS_PROFILE
```

Ideally, iam_profile_name could be set for the provisioner or verifier - and could be different.

**Comment by aaron-lane** [comment]
Hey @danwiltshire! Thank you for your interest in the project.

I'm hesitant to the idea of adding provider-specific inputs to the KT configuration file when there are other options to manage the inputs, namely environment variables or Terraform provider configuration. I think it's important to keep the design of KT focused on the orchestration of creating and verifying infrastructure while remaining agnostic to how the underlying Terraform process handles authentication. Does that make sense?

**Comment by danwiltshire** [comment]
No problem.  I imagine this will probably just effect distributed environments.  Either way, I've written a bash script which works for me.
```bash
#!/bin/bash

current_workspace=$(terraform workspace show)
bundler exec kitchen converge
export AWS_PROFILE=kitchen-terraform-default-aws # use profile that has access to test env
bundler exec kitchen verify
unset AWS_PROFILE # use [default] credentials which has assumerole rights
bundler exec kitchen destroy
terraform workspace select $current_workspace
```
