### ISSUE TITLE
Feature Request - Github Action

### ISSUE THREAD

**Issue by dmedeiros204** [newcontext-oss/kitchen-terraform#423]
I'm not sure if this is its own github action or an extension of this one 

https://github.com/actionshub/test-kitchen

But I'd like to be able to run this addon using a github action.

**Comment by aaron-lane** [comment]
Hi @dmedeiros204! Thank you for your interest in the project.

Kitchen-Terraform is just a plugin for Kitchen (formerly Test Kitchen), which means that you should be able to use the GitHub action that you linked to test with Kitchen-Terraform, assuming that you are able to install the dependencies within the container.
