### ISSUE TITLE
Q / Error: can't modify frozen String while using "old" azurerm_* resources within kitchen-terraform CI execution

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#424]
Hi,
I'd opened this within the inspec-azure repo however got the impression it might be rather a kitchen-terraform issue.
We've upgraded from inspecv3 to inspecv4 and also bumped up inspec-azure profile. While running kitchen-terraform (5.5.0) within our CI system and using (deprecated) azurerm_* profile resources those fail with such an error:

```
2:04:13  Profile: default
2:04:13  Version: (not specified)
2:04:13  Target:  azure://****
2:04:13  
2:04:13    ×  default: Test Suite: 'default'
2:04:13       ×  Control Source Code Error /tmp/code/test/integration/default/controls/default.rb:35 
2:04:13       can't modify frozen String
2:04:13  
2:04:13  
2:04:13  Profile: Azure Resource Pack (inspec-azure)
2:04:13  Version: 1.35.0
2:04:13  Target:  azure://****
2:04:13  
2:04:13       No tests executed.
2:04:13  
2:04:13  Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
2:04:13  Test Summary: 0 successful, 1 failure, 0 skipped
```

inspec 4.23.11
inspec-azure 1.33.2 / 1.35.0

I'm a bit lost how to track this down to it's real root cause though.

REF: inspec-azure issue: https://github.com/inspec/inspec-azure/issues/333

**Comment by tbugfinder** [comment]
[kt-debug-output.txt](https://github.com/newcontext-oss/kitchen-terraform/files/5532347/kt-debug-output.txt)

**Comment by tbugfinder** [comment]
I've enabled RUBYOPT=''--debug=frozen-string-literal" and right now it looks like the error is raised in inspec-azure resource pack.

**Comment by tbugfinder** [comment]
I'm still only able to create this error within CI and running kitchen. Not sure how to trace it down as inspec-azure code seems to be ok.

**Comment by aaron-lane** [comment]
Hello again, @tbugfinder!

Are you able to share the contents of `test/integration/default/controls/default`?

**Comment by aaron-lane** [comment]
Sorry, I see you already provided that in the associated issue. Did you attempt to narrow down the list of variables? Like, only changing the InSpec version or inspec-azure version or the resource used? Kitchen-Terraform uses the frozen string feature in every file so it seems unlikely that a string modification issue is coming from within the plugin library but hasn't been caught by our testing. I suspect that the line of the helper library linked in the other issue isn't where the failed manipulation is happening but rather where the source of the string is.

**Comment by tbugfinder** [comment]
I'm adding it here too for easier review:
```
control 'default' do
  impact 1.0
  title  "Test Suite: 'default'"

  describe azurerm_resource_groups.where(name: rgname) do
    it { should exist }
  end
end
```

**Comment by tbugfinder** [comment]
So far I tried ruby 2.6.1 and ruby 2.6.6, inspec 4.23.11 and inspec 4.23.15, inspec-azure 1.33.2 and 1.35.0.

I agree that I have to find the root of the frozen string.

As you mentioned "Kitchen-Terraform uses the frozen string feature in every file" should kitchen terraform run with the following ruby options without any errors?
`RUBYOPT=--enable-frozen-string-literal --debug=frozen-string-literal`

**Comment by tbugfinder** [comment]
Well and by that find the difference between CI and development server configuration. Although I think tooling, Gem locking, version locking should end up in having equal environments.

**Comment by tbugfinder** [comment]
After adding `.dup` to line: https://github.com/inspec/inspec-azure/blob/v1.37.0/libraries/azure_resource_groups.rb#L76

CI system is happy:
```
 DEPRECATION: `azurerm_resource_groups` uses the new resource `azure_resource_groups` under the hood. azurerm_resource_groups will be deprecated soon and it is advised to switch to the fully backward compatible new resource. Please see the documentation for the additional features available.
 
 Profile: default
 Version: 1.0.0
 Target:  azure://****
 
   ×  default: Test Suite: 'default'
      ×  Azure Resource Groups - api_version: 2020-07-01 latest /resourcegroups/ /resourcegroups/ with name start_with? "InSpec" is expected to exist
      expected Azure Resource Groups - api_version: 2020-07-01 latest /resourcegroups/ /resourcegroups/ with name start_with? "InSpec" to exist
 
 
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.37.0
 Target:  azure://****
 
      No tests executed.
 
 Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
 Test Summary: 0 successful, 1 failure, 0 skipped
```

**Comment by aaron-lane** [comment]
> As you mentioned "Kitchen-Terraform uses the frozen string feature in every file" should kitchen terraform run with the following ruby options without any errors?
> `RUBYOPT=--enable-frozen-string-literal --debug=frozen-string-literal`

Yes,  those options should not have an impact on the behaviour of Kitchen-Terraform (as I understand it) because each source file already includes the special `# frozen_string_literal: true` comment at their beginnings.

Any way, I'm glad that you seem to have found the root cause in inspec-azure!

**Comment by tbugfinder** [comment]
Well,
there's still this question why the frozen string issue is in combination with kitchen-terraform but not if inspec is used.
```kitchen-terraform
 $$$$$$ Verifying the 'azure' system...
 
 Profile: default
 Version: 1.0.0
 Target:  azure://****
 
   ×  default: Test Suite: 'default'
      ×  Control Source Code Error /var/jenkins_home/workspace/tests/ci@2/blueprint-azure-resource-group/test/integration/default/controls/default.rb:17 
      can't modify frozen String
 
 
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.33.2
 Target:  azure://****
 
      No tests executed.
 
 Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
```

and inspec
```inspec
 [2020-11-15T19:20:08+00:00] WARN: DEPRECATION: `azurerm_resource_groups` uses the new resource `azure_resource_groups` under the hood. azurerm_resource_groups will be deprecated soon and it is advised to switch to the fully backward compatible new resource. Please see the documentation for the additional features available.
 
 Profile: default
 Version: 1.0.0
 Target:  azure://****
 
   ×  default: Test Suite: 'default'
      ×  Azure Resource Groups - api_version: 2020-07-01 latest /resourcegroups/ /resourcegroups/ with name start_with? "InSpec" is expected to exist
      expected Azure Resource Groups - api_version: 2020-07-01 latest /resourcegroups/ /resourcegroups/ with name start_with? "InSpec" to exist
 
 
 Profile: Azure Resource Pack (inspec-azure)
 Version: 1.33.2
 Target:  azure://****
 
      No tests executed.
 
 Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
```

I'll try to find the kitchen-terraform code line which maybe processes the output.

**Comment by tbugfinder** [comment]
Ok,
using debug I'm ending up in
```
Exception `FrozenError' at /.../vendor/bundle/ruby/2.6.0/gems/test-kitchen-2.7.2/lib/kitchen/logger.rb:300 - can't modify frozen String, created at libraries/backend/helpers.rb:340
```

logger.rb:300 is:
`msg.concat("\n")`

**Comment by tbugfinder** [comment]
Finally it got patched in Test-Kirchen.
