### ISSUE TITLE
terraform 0.14 (just released) support

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#427]
Please provide terraform 0.14 support as it just was released.

https://github.com/hashicorp/terraform/blob/v0.14/CHANGELOG.md

**Comment by edwardbartholomew** [comment]
Thanks for your continued interest in kitchen-terraform @tbugfinder  

Looks like @brandocorp just submitted a PR for this, will take a look at it today.

**Comment by tbugfinder** [comment]
Hi @aaron-lane 
as the PR was merged.
https://github.com/newcontext-oss/kitchen-terraform/pull/428
Should this also pop up as a new release within the Github releases?

**Comment by tbugfinder** [comment]
It is on rubygems, though.

**Comment by edwardbartholomew** [comment]
Thanks @tbugfinder - I had previously created the tag which triggers a build and push to rubygems but hadn't created the release in GitHub. I have created the release and now shows as a new release.
