### ISSUE TITLE
kitchen-terraform silently passes if terraform outputs are not correct.

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#440]
Hi,

in case a module defines an invalid output kitchen terraform finishes successfully, although execution of `terraform plan` in the fixture directory raises an error.

Replication case.

add/edit outputs.tf in root folder.
```
output "not_existent_reference" {
  description = "Test output."
  value       = var.nodefinitionasvariable
}
```

Version: kitchen-terraform 5.6.0/5.7.0/5.7.1, tested with terraform 0.12.29, 0.13.5, 0.14.7.

Thanks

**Comment by tbugfinder** [comment]
I've created a demo repo:
https://github.com/tbugfinder/kttfsample/blob/demo440/outputs.tf#L12-L15

Kitchen terraform runs apply and verify successfully however terraform plan in test/fixture/default errors out:
```
$ terraform plan

Error: Reference to undeclared input variable

  on ../../../outputs.tf line 14, in output "output_doesnt_exits":
  14:   value       = var.notdefined

An input variable with the name "notdefined" has not been declared. This
variable can be declared with a variable "notdefined" {} block.


```

**Comment by tbugfinder** [comment]
kitchen-terraform is using `TF_WARN_OUTPUT_ERRORS=1 terraform plan` by default.
Having this in place such errors are not raised.
I understand that this was added to kitchen-terraform by intention however if such errors not catched during development cycles (running kitchen) then those errors are raised later.

Which options do we have to override this environment setting?
So maybe `terraform plan` could be invoked without this ENV setting but subsequent commands use it?


https://www.terraform.io/guides/running-terraform-in-automation.html#controlling-terraform-output-in-automation

**Comment by aaron-lane** [comment]
Hmm, looks like we introduced a regression at some point by setting that variable again. It should be a simple task to remove it!

**Comment by aaron-lane** [comment]
I'm going to do a bit of digging tonight to make sure I'm not misrepresenting the situation. I think we do want the variable set on some circumstances, like `destroy`, to allow `kitchen test` to operate successfully.

**Comment by tbugfinder** [comment]
I don't have a test-case or evidence however I share thoughts about `command`.
In my case it would be sufficient if a `terraform plan` would just run before. Most probably I could add that to the lifecycle pre_converge.
