### ISSUE TITLE
Q: VerifyVersion available as ENV setting

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#444]
Hi,
as terraform development speed increased, it would be beneficial to set the `verify_version = false` within CI environments easily.
Is there an ENV setting which would immediately toggle the version lock check?

Thanks

**Comment by aaron-lane** [comment]
👋🏻 Unfortunately, the Kitchen-Terraform configuration options are controlled only through the Kitchen configuration file. There are some alternatives for how you can accomplish more dynamic configuration here: https://kitchen.ci/docs/reference/configuration/

**Comment by tbugfinder** [comment]
Ah, that sounds good. I'll try:
`verify_version: <%= ENV['KITCHEN_TERRAFORM_VERIFY_VERSION'] || "true" %>`

**Comment by tbugfinder** [comment]
Works for me however reveals that 0.15beta1 requires kitchen-terraform updates.
