### ISSUE TITLE
support for (upcoming) terraform 0.15.x (includes CLI changes)

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#445]
Hi,

terraform 0.15beta1 includes few changes to the terraform CLI (e.g. terraform init -lock, -lock-timeout) which raise an error while running kitchen terraform with `version_verify=false` .
It might be beneficial to prepare ahead for running terraform using different CLI options dependent on terraform versions. 

Ref:
https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md

**Comment by tbugfinder** [comment]
It just was released.

**Comment by brettcurtis** [comment]
correct me if I'm wrong but this means we can't use .15 right now with kitchen at all or is there a W/A?

**Comment by aaron-lane** [comment]
@brettcurtis unfortunately, you are correct. None of the maintainers have had an opportunity to implement support for 0.15.

**Comment by brettcurtis** [comment]
Ok we'll kick back to a .14 version. Thanks for the info.

**Comment by aaron-lane** [comment]
I have started work on the implementation 🥳

**Comment by wyardley** [comment]
@aaron-lane I know this is probably somewhat involved, but any idea when this is likely to ship?

**Comment by aaron-lane** [comment]
@wyardley Optimistically, by the end of this week 🤞🏼 but it's a "when I have time" sort of process of course.

**Comment by aaron-lane** [comment]
Work is on the https://github.com/newcontext-oss/kitchen-terraform/tree/aaron-lane-terraform-0-15 branch, for the curious.
