### ISSUE TITLE
Ruby 3.0 support

### ISSUE THREAD

**Issue by ramereth** [newcontext-oss/kitchen-terraform#456]
Chef Workstation now ships with Ruby 3.0 and kitchen-terraform is no longer able to be installed:

```
kitchen-terraform-5.8.0 requires Ruby version >= 2.4, < 2.8. The current ruby version is 3.0.1.64.
```

I'm not sure how much work is needed to add support but it would be great to get a new release out soon that supports Ruby 3.0.

**Comment by ramereth** [comment]
Any updates on when you might be able to fix this? I might be able to have someone take a look on our end but it seemed to involve a lot of work with all the dependencies when I checked myself.

**Comment by aaron-lane** [comment]
Hi @ramereth! I apologize for the delay in responding. I'm going to start the investigation presently 🎉

**Comment by aaron-lane** [comment]
@ramereth Would you be able to test the branch [aaron-lane-ruby-3](https://github.com/newcontext-oss/kitchen-terraform/tree/aaron-lane-ruby-3)? I think it is ready to ship.

**Comment by ramereth** [comment]
@aaron-lane can you loosen the deps on `delegate` please? I'm having this issue when trying to use the latest workstation:

```
Unable to activate kitchen-terraform-5.8.0, because delegate-0.2.0 conflicts with delegate (~> 0.1.0)
```

**Comment by aaron-lane** [comment]
@ramereth Done!

**Comment by ramereth** [comment]
@aaron-lane confirmed that works on my end! Thanks!

**Comment by aaron-lane** [comment]
Thanks @ramereth! I'll try to get this released today.
