### ISSUE TITLE
Is it possible to test multiple versions of Terraform with kitchen-terraform?

### ISSUE THREAD

**Issue by nshenry03** [newcontext-oss/kitchen-terraform#466]
Hello, in SaltStack (w/ `kitchen-salt`), it's possible to test many different versions of SaltStack on many different operating systems using [platforms](https://github.com/saltstack-formulas/template-formula/blob/master/kitchen.yml#L23-L458) (and Docker images).  Is it possible to configure `kitchen-terraform` to test multiple Terraform versions with `tfenv` or Docker?  Or are we only able to use the version of Terraform currently installed on a dev's machine (and CI/CD)?

**Comment by aaron-lane** [comment]
Hi @nshenry03! Currently, Kitchen-Terraform is limited to using whatever version of Terraform is installed on the workstation. That being said, you could set `driver.client` to a different instance of Terraform for each platform, so long as they each have different pathnames.

An example of setting `driver.client` for a specific platform is available in our [tests](https://github.com/newcontext-oss/kitchen-terraform/blob/master/kitchen.yml#L9-L12).

**Comment by nshenry03** [comment]
Hey Aaron, thanks for the quick response!

So looks like we could ask developers to setup their system something like this (and we could do the same on our CI servers):

```NOFORMAT
hnicholas@hnicholas-a01:~/.local/bin$ ll terraform-*
lrwxr-xr-x  1 hnicholas  staff  56 Dec  9 14:44 terraform-0-14-11@ -> /usr/local/Cellar/tfenv/2.2.2/versions/0.14.11/terraform
lrwxr-xr-x  1 hnicholas  staff  54 Dec  9 14:45 terraform-1-1-0@ -> /usr/local/Cellar/tfenv/2.2.2/versions/1.1.0/terraform
```

```NOFORMAT
hnicholas@hnicholas-a01:~$ terraform-0-14-11 --version
Terraform v0.14.11

Your version of Terraform is out of date! The latest version
is 1.1.0. You can update by downloading from https://www.terraform.io/downloads.html
```

```NOFORMAT
hnicholas@hnicholas-a01:~$ terraform-1-1-0 --version
Terraform v1.1.0
on darwin_amd64
```

Then we could setup `kitchen.yml` something like this:

```YAML
platforms:
  - name:terraform-0-14-11
    driver:
      client: terraform-0-14-11
  - name:terraform-1-1-0
    driver:
      client: terraform-1-1-0
```

And that should work?  Cool, we'll give that a shot and let you know how it turns out. Thanks for the help.
