### ISSUE TITLE
support terraform 1.1.x

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#467]
https://github.com/newcontext-oss/kitchen-terraform/blob/254ae2b17a74c8027a1500de3db1eab534fb834f/kitchen-terraform.gemspec#L49

Hello, 

it would be nice if terraform 1.1.x would be supported without disabling the version check.
Thank you so much.

Best

**Comment by jkroepke** [comment]
Are there known incompatibilities between kitchen-terraform and terraform 1.1?

**Comment by aaron-lane** [comment]
@jkroepke not to my knowledge. The update should be fairly simple: I'll try to release a new version tonight.
