### ISSUE TITLE
Add Inspec 5.x support

### ISSUE THREAD

**Issue by wyardley** [newcontext-oss/kitchen-terraform#479]
I'm not sure if it's intentional, but is there a reason inspec 5.x isn't supported? Is there a plan for it to be at some point?

```
    kitchen-terraform (~> 6.1.0) was resolved to 6.1.0, which depends on
      inspec (>= 3, != 4.24.26, != 4.24.28, != 4.24.32, < 5)
```

**Comment by aaron-lane** [comment]
Hey @wyardley 👋🏼 InSpec 5 isn't supported currently because it wasn't released when Kitchen-Terraform was last released. I don't think there are any technical blockers to implementing the support; someone just needs to find the time to do it 😁

**Comment by wyardley** [comment]
Thanks! Appreciate the answer. Feel free to close this if needed. I can also try to make a PR for it.

I’ve been trying to understand their versioning more, or to get a list of things that might behave differently, but haven’t had much luck so far

**Comment by wyardley** [comment]
@aaron-lane let me know if my PR looks right (I can keep Inspec 3 support if you want, but to me, probably makes sense to drop it?)
