### ISSUE TITLE
Compatibility with Terraspace

### ISSUE THREAD

**Issue by duncanwraight** [newcontext-oss/kitchen-terraform#486]
Hi folks

Is there any way we could use kitchen-terraform with Terraspace?

It's a Ruby wrapper to allow layering of configuration. Makes TF repositories cleaner and more DRY-friendly: https://terraspace.cloud/

Instead of terraform plan, terraform apply etc. we use terraspace up <<stack name>>, e.g. terraform up eks-cluster.

Could we override the executable commands used?

**Comment by aaron-lane** [comment]
Hi @duncanwraight 👋🏼 

It is currently possible to override the executable client using the driver's [client](https://www.rubydoc.info/github/newcontext-oss/kitchen-terraform/Kitchen/Terraform/ConfigAttribute/Client) attribute, but that does not include overriding the specific commands issued. If you are able to provide the analogous Terraspace commands that should be invoked to implement the same workflow as exists using Terraform then we may be able to determine how to support it 🤔
