### ISSUE TITLE
Bastion host support

### ISSUE THREAD

**Issue by jamtur01** [newcontext-oss/kitchen-terraform#50]
A lot of configurations use something like a bastion host or VPN Gateway to bounce traffic or connections through. It'd be good if `kitchen-terraform` supported [Terraform's concept of a bastion host](https://www.terraform.io/docs/provisioners/connection.html#bastion_host).

**Comment by toddmichael** [comment]
Would love to see this as well. Loving me some `kitchen-terraform` and trying to use in my VPC NAT refactor project. Unfortunately, can't connect to my private instance to test without Bastion support.  Again, thanks for the fantastic project. Cheers.

**Comment by ncs-alane** [comment]
Hi @jamtur01 and @toddmichael:

Thanks for your interest in the project!

The ability to use a bastion host requires support in InSpec. It has not been implemented yet but there is an [open issue](https://github.com/chef/inspec/issues/431). Once it is available, we'll make sure to support it.

**Comment by dustyburwell** [comment]
The test-kitchen ssh connections appear to respect any configuration you have in your user's ssh config. So, you can set up bastions with ProxyCommand.

**Comment by ncs-alane** [comment]
@jamtur01 or @toddmichael: does @dustyburwell's solution work for you? We can document the solution while waiting on the implementation in InSpec.

**Comment by jamtur01** [comment]
As a workaround, it's fine for me until we have a real solution that's more idempotent and portable.
