### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS: credentials type 'external_account' is not supported

### ISSUE THREAD

**Issue by brettcurtis** [newcontext-oss/kitchen-terraform#514]
Just in case this is something here: https://github.com/inspec/inspec/issues/6500, I'm not exactly sure where the issue is?

**Comment by aaron-lane** [comment]
I don't believe this would be an issue within Kitchen-Terraform: it just invokes InSpec. It looks like it's an incompatibility with whichever GCP-related library it is invoking. 🤔

**Comment by brettcurtis** [comment]
Yeah I agree, figured I'd check. I'll close this one out.

**Comment by brettcurtis** [comment]
I'm going to add this here in case it's useful for anyone searching around: https://github.com/inspec/inspec-gcp/issues/437

I tried messing with the Gemfile to pull more recent versions, but I ended up in dependency hell. It looks like inspec is using a 3-year-old googleauth library.
