### ISSUE TITLE
Support for terraform apply parallelism option

### ISSUE THREAD

**Issue by s3lehtin** [newcontext-oss/kitchen-terraform#52]
Could you enable support for specifying -parallelism n option in terraform apply command. AzureRM seems to be a bit picky when running with default value (10) on jenkins. I manually added -parallelism 1 to apply_command.rb options and AzureRM resources are now being created without problems.

https://www.terraform.io/docs/commands/apply.html#_parallelism_n

Thanks! 
-Sami

**Comment by ncs-alane** [comment]
Hi Sami:

Thanks for your interest in the project! Adding a parallelism option to the configuration file should be should be simple. We'll try to get that in to the next release.
