### ISSUE TITLE
postpone date to archive project

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#530]
Hello,

we've been locking into `terraform test`.
Overall there are few differences kitchen-terraform covers compared to the terraform test.
Also terraform test does not provide proper junit output, but it's an experimental feature.

Overall we are just wondering if this project could get some additional months and another release update?

Thanks&Best

**Comment by aaron-lane** [comment]
Hello again @tbugfinder 👋🏼 

Unfortunately, I do not have the time or inclination to continue maintaining the project, as I have not personally used Kitchen-Terraform in several years. If there are pressing bugs to be fixed then I will try my best to resolve those, but I am not in a position to continue with new feature work and the project will still be archived at the beginning of October.

If folks are interested in carrying on development of Kitchen-Terraform then I fully encourage them to create a fork and keep the project alive under a new name. However, in the interest of the security of our users, I will not be transferring ownership of this repository or the Ruby Gems entry to another party.

I apologize if my response is undesirable, but I feel like this is the fairest solution for both myself and our users.
