### ISSUE TITLE
Support specs for provider APIs

### ISSUE THREAD

**Issue by ncs-alane** [newcontext-oss/kitchen-terraform#7]
This feature will allow kitchen-terraform to test elements of the provider API based on Terraform configuration, like the existence of a security group or the properties of an IAM role. There are a couple of gems like inspec-aws that should serve this purpose, but some changes to the verifier will be necessary to support running tests from the localhost.

**Comment by nellshamrell** [comment]
Such as security groups?  IAM users?  What features are you thinking of supporting?

**Comment by ncs-alane** [comment]
@nellshamrell: updated the description!
