### ISSUE TITLE
tests fails with Message: key not found: "value"

### ISSUE THREAD

**Issue by bru2code** [newcontext-oss/kitchen-terraform#73]
Hi,  My tests using kitchen-terraform keeps on failing with above error during verify. Have attached information below, would be useful if there is a better error messages to debug. Appreciate any suggestions here.

1) .kitchen.yml 
---
driver:
  name: terraform

provisioner:
  name: terraform
  variable_files:
    - terraform.tfvars

platforms:
   - name: redhat

transport:
  name: ssh
  ssh_key: infra-deployer.pem

verifier:
  name: terraform
  format: doc
  groups:
  - name: default
  hostnames: ubm_dev_lsf_public_dns
  username: ec2-user

suites:
- name: default

2) $ bundle exec kitchen list
       Terraform v0.7.13

       Your version of Terraform is out of date! The latest version
       is 0.8.1. You can update by downloading from www.terraform.io
Instance        Driver     Provisioner  Verifier   Transport  Last Action  Last Error
default-redhat  Terraform  Terraform    Terraform  Ssh        Set Up       KeyError

3) $ bundle exec kitchen converge
-----> Starting Kitchen (v1.14.2)
       Terraform v0.7.13

       Your version of Terraform is out of date! The latest version
       is 0.8.1. You can update by downloading from www.terraform.io
-----> Converging <default-redhat>...
.
.
.
.
.
      Finished converging <default-redhat> (0m12.40s).
-----> Kitchen is finished. (0m13.63s)

4) Checked "terraform show" output to confirm below just to be sure it is avaiable 
ubm_dev_lsf_public_dns = ssh-ubm-dev.sw.xyz.com

5) $ bundle exec kitchen verify
-----> Starting Kitchen (v1.14.2)
       Terraform v0.7.13

       Your version of Terraform is out of date! The latest version
       is 0.8.1. You can update by downloading from www.terraform.io
-----> Setting up <default-redhat>...
       Finished setting up <default-redhat> (0m0.00s).
-----> Verifying <default-redhat>...
       Terraform v0.7.13

       Your version of Terraform is out of date! The latest version
.
.
.
   
           "ubm_dev_lsf_public_dns": {
        "sensitive": false,
        "type": "string",
        "value": "ssh-ubm-dev.sw.xyz.com"
           },

.
.
.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [key not found: "value"] on default-redhat
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by ncs-alane** [comment]
Hi @bru2code:

Thanks for your interest in the project! 

Can you provide the output of `bundle exec kitchen verify --level debug`?

**Comment by ncs-alane** [comment]
@bru2code: are you still experiencing an error?

**Comment by ncs-alane** [comment]
@bru2code: please reopen this issue if you still need help.
