### ISSUE TITLE
Add configuration option to specify Terraform CLI pathname (support using terragrunt rather than hardcoding the terraform binary's filename)

### ISSUE THREAD

**Issue by elijah** [newcontext-oss/kitchen-terraform#95]
I'd like to be able to use the terragrunt binary rather than the (currently hardcoded in command.rb...) terraform binary.  

Terragrunt adds a locking shim on top of terraform, but is otherwise simply a pass-through for terraform commands.

The big win here would be to enable using inheritance in tfstate files - a la the "Isolation" section of https://blog.gruntwork.io/how-to-manage-terraform-state-28f5697e68fa#.12vsq42ng .  Using terraform in the raw for this doesn't work too well (ha), and having support for terragrunt would make it easier to use this organizational pattern.

I'd like to be able to set, e.g. 'provisioner'->'command_name' in .kitchen.yml to terragrunt, and have it "just work" on test kitchen runs.  [Modulo the need to set up a storage for the terragrunt remote state file, et cetera... the things that one would expect.]

best,

--e

**Comment by qvallance-ctc** [comment]
Mitchell just announced that the next version of Terraform will support locking for remote state.
https://twitter.com/mitchellh/status/831593917434834944

> [@mitchellh](https://twitter.com/mitchellh)
The next version of Terraform performs state locking automatically! Works with local files, S3, Consul, and TF Enterprise.

**Comment by ncs-alane** [comment]
A configuration option to specify the pathname of an executable that implements the necessary Terraform CLI subcommands is planned for the next release! 🎺

**Comment by lmayorga1980** [comment]
So it seems like calling `terragrunt` it's supported. Any examples or references?

**Comment by aaron-lane** [comment]
@lmayorga1980 we use Terragrunt when testing the project on MacOS: https://github.com/newcontext-oss/kitchen-terraform/blob/master/kitchen.yml#L13
