### ISSUE TITLE
Passing nil, or [nil] to Net::SSH.start is deprecated for keys: forward_agent

### ISSUE THREAD

**Issue by qvallance-ctc** [newcontext-oss/kitchen-terraform#96]
## Description

Getting warning messages from Net::SSH.start when inspec attempts to ssh to GCE VM deployed by Terraform.

## kitchen-terraform Version
```ruby
kitchen-terraform (0.5.0)
```

## Terraform Version
```ruby
Terraform v0.8.6
```

## kitchen-inspec Version
```ruby
kitchen-inspec (0.17.0)
```

## Kitchen Version
```ruby
Test Kitchen version 1.15.0
```

## Inspec Version
```ruby
inspec (1.14.1)
```

## Ruby Version
```ruby
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
```

## Platform Version
```
Alpine Linux 3.4.4
```

## Replication Case

When inspec attempts to ssh to the Google Compute VM, deployed by terraform, warnings are displayed from Net:SSH.start, about receiving nil for the forward_agent key, which is deprecated.

## Kitchen Output

```ruby
/usr/local/bundle/gems/train-0.22.1/lib/train/transports/ssh_connection.rb:188:in `establish_connection': Passing nil, or [nil] to Net::SSH.start is deprecated for keys: forward_agent
/usr/local/bundle/gems/train-0.22.1/lib/train/transports/ssh_connection.rb:188:in `establish_connection': Passing nil, or [nil] to Net::SSH.start is deprecated for keys: forward_agent
/usr/local/bundle/gems/train-0.22.1/lib/train/transports/ssh_connection.rb:188:in `establish_connection': Passing nil, or [nil] to Net::SSH.start is deprecated for keys: forward_agent
```

## Kitchen Diagnose

https://gist.github.com/qvallance-ctc/e1a8d2d48c5beede3882e1a616027b0d

**Comment by ncs-alane** [comment]
@qvallance-ctc: thank you for your interest in the project, and the very detailed report!

I will see if there is a way to satisfy the warning in the next release.

**Comment by ncs-alane** [comment]
I looked at `Train::Transports::SSH::Connection` and it appears that this warning has to be solved in that code base.

**Comment by qvallance-ctc** [comment]
Thanks.  Just wanted to be sure.  I'll open an issue against that code base.
